# Call Y Haplogroups
Leipzig Cluster, Using fast pulldown

In [1]:
import numpy as np
import os  # For Saving to Folder
import pandas as pd
import matplotlib.pyplot as plt

import socket
import os as os
import sys as sys
import multiprocessing as mp
from pysam import AlignmentFile

### For Arial Font
from matplotlib import rcParams
rcParams['font.family'] = 'sans-serif'   # Set the defaul
### Make sure to have the font installed (it is on cluster for Harald)
rcParams['font.sans-serif'] = ['Arial']

socket_name = socket.gethostname()
print(socket_name)

if socket_name.startswith("compute-"):
    print("HSM Computational partition detected.")
    path = "/n/groups/reich/hringbauer/git/y_chrom/"  # The Path on Midway Cluster
    
elif socket_name.startswith("bionc") or socket_name.startswith("hpc"):
    print("Leipzig Cluster detected!")
    path = "/mnt/archgen/users/hringbauer/git/y_chrom/"
    
else:
    raise RuntimeWarning("Not compatible machine. Check!!")

os.chdir(path)  # Set the right Path (in line with Atom default)
# Show the current working directory. Should be HAPSBURG/Notebooks/ParallelRuns
print(os.getcwd())
print(f"CPU Count: {mp.cpu_count()}")
print(sys.version)

hpc030
Leipzig Cluster detected!
/mnt/archgen/users/hringbauer/git/y_chrom
CPU Count: 128
3.12.3 (main, Jan 22 2026, 20:57:42) [GCC 13.3.0]

### Load functions which are needed

In [2]:
def load_counts(path_counts, coerce=True):
    """Load Count file and return Dataframe"""
    df_t = pd.read_csv(path_counts, header=None, delim_whitespace=True)
    df_t.columns = ["snp", "chr", "pos", "ref_all", "alt_all", "drop", "iid", "ref", "alt"]
    
    if coerce:
        for col in ["pos", "ref", "alt"]:
            df_t[col] = pd.to_numeric(df_t[col], errors="coerce")
            
    df_t = df_t.drop(columns="drop")
    return df_t

def load_snp_file_ISOGG(path_snps = "./data/all_snps.csv", 
                    col_pos = 'Build 37 Number', unique=True):
    """Return Dataframe in Eigenstrat Format,
    filtered for biallelic SNPs.
    unique: Whether to keep a """
    df_raw = pd.read_csv(path_snps)
    print(df_raw.columns)
    print(f"Loaded {len(df_raw)} SNPs")

    ### Process the positions
    pos = df_raw[col_pos]
    df_raw["pos"] = pd.to_numeric(pos, errors="coerce")

    idx = ~df_raw["pos"].isna()
    print(f"# Positions available: {np.sum(idx)}")
    df = df_raw[idx].reset_index(drop=True)
    df["pos"]=df["pos"].astype("int")

    idx_bi= (df["Mutation Info"].str.len()==4)
    print(f"# Biallelic SNPs: {np.sum(idx_bi)}")
    df = df[idx_bi].reset_index(drop=True)
    df["ref"] = df["Mutation Info"].str[0]
    df["alt"] = df["Mutation Info"].str[3]
    df["chrom"] = "Y"

    cols = ["Name", "chrom", "pos", "ref", "alt", 
            'Subgroup Name', 'Alternate Names', 'rs numbers']
    df = df[cols]
    df = df.replace(regex=[' ','\n'], value='_')
    ### Sort by position
    df = df.sort_values(by="pos")
    
    ### Keep only SNPs where Ref and Alt Different
    idx_same = (df["ref"]==df["alt"])
    df = df[~idx_same]
    print(f"# Ref & Alt different: {len(df)}")
    
    ### Keep only ACTG
    snps_acceptable = ["A", "C", "T", "G"]
    idx_ref = df["ref"].isin(snps_acceptable)
    idx_alt = df["alt"].isin(snps_acceptable)
    idx_both = idx_ref & idx_alt
    df = df[idx_both]
    print(f"# Ref & Alt ACTG: {len(df)}")
    
    ### Keep Unique Values
    if unique:
        idx_dup = df.duplicated(subset=["pos", "ref", "alt"], keep="first")
        df = df[~idx_dup]
        print(f"# Unique SNP positions: {len(df)}")
    
    ### Remove duplicate Names
    #idx_dup = df.duplicated(subset="Name", keep=False)
    #df = df[~idx_dup]
    #print(f"# Unique Names: {len(df)}")
    return df.copy().reset_index(drop=True)


################################################
### Calling Ys

def ref_alt_count(df_ch, bases=["A", "C", "G", "T"]):
    """Count Ref and Alt alleles in Dataframe df_ch
    with ref, alt, A, C, G, T fields and enter new columns
    ref# and alt#"""
    df_ch["ref#"]=0
    df_ch["alt#"]=0

    for p in bases:
        idx = df_ch["ref"] == p
        df_ch.loc[idx, "ref#"] = df_ch.loc[idx, p]

        idx = df_ch["alt"] == p
        df_ch.loc[idx, "alt#"] = df_ch.loc[idx, p]
    return df_ch

def pulldown_bamtable(path_bam = "", o_file = "",                   
                      bamtable = "/home/pruefer/bin/BamTable",
                      snip5=0, snip3=0,
                      path_bed = "/mnt/archgen/users/hringbauer/git/y_chrom/data/isogg_snps.bed"):
    """Pulldown a BAM at path_bam to o_file using bamtable and the bed a path_bed."""
    !$bamtable -F -A --snip5=$snip5 --snip3=$snip3 -f $path_bed $path_bam > $o_file
    

def call_y_bam(path_bam="", df=[],
               path_bed = "/mnt/archgen/users/hringbauer/git/y_chrom/data/isogg_snps.bed",
               path_temp="/mnt/archgen/users/hringbauer/git/y_chrom/temp/temp.tsv",
               snip5=0, snip3=0):
    """Creates the Call Table from a .bam file"""
    
    ### Create the Pulldown
    pulldown_bamtable(path_bam = path_bam,
                      path_bed = path_bed, 
                      snip5=snip5, snip3=snip3,
                      o_file = path_temp)

    df1 = pd.read_csv(path_temp, sep="\t", header=None)
    df1.columns = ["chrom", "pos", "A", "C", "G", "T"]
    idx = df1["chrom"]=="chrY"
    if np.sum(idx)>0:
        print(f"Changing {np.sum(idx)} ChrY -> Y")
        df1.loc[idx, "chrom"] = "Y"
        
    df2 = pd.merge(df, df1, on=["chrom", "pos"])
    
    ### Coverage Statistics
    cov = df1[["A", "C", "G", "T"]].values
    cov1 = np.sum(cov, axis=1)
    print(f"Average Coverage: {np.sum(cov1)/len(df):.4f}x")
    print(f"#Sites covered: {np.sum(cov1>0)}/{len(df)}")
    
    ### Establish Ref and Alt allele
    df_ch = ref_alt_count(df2, bases=["A", "C", "G", "T"])

    ### Identify Derived    
    idx_der = df_ch["alt#"]>df_ch["ref#"]
    print(f"#Derived Loci: \n{np.sum(idx_der)} / {np.sum(cov1>0)} covered>0")
    
    df_der = df_ch[idx_der].sort_values(by="Subgroup Name").reset_index(drop=True).copy()
    
    return df_ch, df_der 

def mismatch_path(s, df):
    """Look for all mismatches in path up to s"""
    ls = [s, s+"~"]

    for i in range(1,len(s)):
        ls+= [s[:-i], s[:-i]+"~"]

    dft = df[df["Subgroup Name"].isin(ls)]
    idx = dft["ref#"]>=dft["alt#"]
    print(f"Mismatches: {np.sum(idx)} / {len(idx)}")
    return dft

###########################
### Functions for browsing Haplogroups

def find_supgroups_der(df, subgroup="", col="Subgroup Name"):
    """Output all real subgroups (but not the orginal one)."""
    dft=df[df[col].str.contains(subgroup)]
    dft2=dft[dft[col]!=subgroup]
    return dft2

def calc_error_rate(df_ch, haploclade="G"):
    """ Calculate Error Rate based on supposedly ancestral clade"""
    dft = df_ch[df_ch["Subgroup Name"].str.startswith(haploclade)]
    der = np.sum(dft["alt#"])
    ref = np.sum(dft["ref#"])
    print((ref,der))
    print(f"Error rate: {der/(ref+der)*100:.4g}%")

# Create a bed file for ISOGG SNPs [one time requirement]

In [3]:
df = load_snp_file_ISOGG("./data/all_snps.csv")
#df = pd.read_csv("./data/y_snps_heinrichII.tsv", sep="\t")
df = df.sort_values(by="pos")

savepath = "./data/isogg_snps.bed"

dft = df[["chrom", "pos"]].copy()
dft["pos1"] = dft["pos"]
dft.to_csv(savepath, sep="\t", index=False, header=None)
print(f"Saved {len(dft)} ISOGG SNPs to {savepath}")

Index(['Name', 'Subgroup Name', 'Alternate Names', 'rs numbers',
       'Build 37 Number', 'Build 38 Number', 'Mutation Info'],
      dtype='object')
Loaded 92035 SNPs
# Positions available: 91881
# Biallelic SNPs: 91814
# Ref & Alt different: 91811
# Ref & Alt ACTG: 91806
# Unique SNP positions: 73148
Saved 73148 ISOGG SNPs to ./data/isogg_snps.bed

In [57]:
df[df["Name"].str.contains("Z17121")]

     Name chrom       pos ref alt  Subgroup Name  Alternate Names  rs numbers
0  Z17121     Y  23800016   T   A            NaN              NaN         NaN

In [31]:
df[df["Subgroup Name"]=="R1b1a1b1a1a2e1"]

       Name chrom       pos ref alt   Subgroup Name Alternate Names rs numbers
43932  DF88     Y  17508792   G   A  R1b1a1b1a1a2e1           S4298        NaN

# Load the BAM path [from Autorun]
Can use this dictionary to look up bam files of individuals

In [4]:
dft = pd.read_csv("/mnt/archgen/users/hringbauer/git/auto_popgen/output/TF/v0.3/bam_paths.tsv", sep="\t")
dft2 = pd.read_csv("/mnt/archgen/users/hringbauer/git/auto_popgen/output/RM/v0.3/bam_paths.tsv", sep="\t")
n = np.sum(dft["bam#"]>0)
bam_dict = dict(zip(dft["iid"], dft["bam_path"]))
bam_dict2 = dict(zip(dft2["iid"], dft2["bam_path"]))
print(f"Loaded {len(dft)} Individuals. With BAM: {n}")
print(f"Loaded {len(dft2)} RM Individuals.")

Loaded 28636 Individuals. With BAM: 17215
Loaded 4607 RM Individuals.

In [5]:
bam_dict["DGB026"]
#bam_dict2["DGB020"]

'/mnt/archgen/Autorun_eager/eager_outputs/TF/DGB/DGB026/trimmed_bam/DGB026_ss.A0101_udgnone.trimmed.bam'

### Prepare the SNP list

In [5]:
df = load_snp_file_ISOGG("./data/all_snps.csv")

Index(['Name', 'Subgroup Name', 'Alternate Names', 'rs numbers',
       'Build 37 Number', 'Build 38 Number', 'Mutation Info'],
      dtype='object')
Loaded 92035 SNPs
# Positions available: 91881
# Biallelic SNPs: 91814
# Ref & Alt different: 91811
# Ref & Alt ACTG: 91806
# Unique SNP positions: 73148

### Run the Y haplogroup calling

In [7]:
%%time
#path_bam = bam_dict2["MDA003"]
path_bam = bam_dict2["KKG002"]

df_ch, df_der = call_y_bam(df=df, 
                           path_bam=path_bam) #A55903 and A55904
len(df_der)

Average Coverage: 5.1489x
#Sites covered: 58158/73148
#Derived Loci:
1030 / 58158 covered>0
CPU times: user 105 ms, sys: 80.4 ms, total: 185 ms
Wall time: 1.42 s

1030

In [15]:
df_der[-100:-50]

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
930,PF4965,Y,15610713,G,T,J2a,CTS4360,NaN,0,0,0,10,0,10
931,CTS4699,Y,15775488,A,G,J2a,PF4909,NaN,0,0,3,0,0,3
932,PF4966,Y,15704139,C,T,J2a,CTS4540,NaN,0,0,0,5,0,5
933,F841,Y,6854256,C,T,J2a,PF4948,NaN,0,0,0,5,0,5
934,CTS9538,Y,18952077,G,A,J2a,PF4919,NaN,1,0,0,0,0,1
935,L505,Y,21970721,G,T,J2a,PF4987,NaN,0,0,0,1,0,1
936,PF4953,Y,7680253,C,G,J2a,NaN,NaN,0,0,6,0,0,6
937,PF4952,Y,7676739,C,T,J2a,NaN,NaN,0,0,0,7,0,7
938,PF5112,Y,23033706,C,T,J2a1,CTS11251,NaN,0,0,0,1,0,1
939,PF4610,Y,22757708,G,C,J2a1,NaN,NaN,0,3,0,0,0,3
940,CTS4403,Y,15632637,G,T,J2a1,PF5096,NaN,0,0,0,7,0,7
941,PF5104,Y,20816211,G,C,J2a1,NaN,NaN,0,8,0,2,0,8
942,PF5105,Y,20836109,A,G,J2a1,NaN,NaN,0,0,9,0,0,9
943,F1227,Y,8465758,C,G,J2a1,NaN,NaN,0,0,14,0,0,14
944,PF5091,Y,8809001,T,C,J2a1,NaN,NaN,0,2,0,0,0,2
945,CTS10711,Y,22715995,C,T,J2a1a,PF5109,NaN,0,0,0,5,0,5
946,FGC2794,Y,7910634,A,G,J2a1a,Z7728;_S10814,NaN,0,0,4,0,0,4
947,CTS2192,Y,14213941,G,A,J2a1a,PF5094,NaN,2,0,0,0,0,2
948,Z1849,Y,8482151,G,T,J2a1a,PF5089,NaN,0,0,0,15,0,15
949,PF5106,Y,21493159,G,A,J2a1a,NaN,NaN,3,0,0,0,0,3
950,PF5114,Y,23402887,A,G,J2a1a,CTS11983,NaN,1,0,6,0,1,6
951,PF4901,Y,9422558,C,A,J2a1a,NaN,NaN,9,0,0,0,0,9
952,S396,Y,23021978,A,G,J2a1a,F4326;_L27;_PF5111,NaN,0,0,2,0,0,2
953,PF5088,Y,8107430,T,C,J2a1a1,NaN,NaN,0,2,0,0,0,2
954,Y20305,Y,17392251,G,A,J2a1a1a2b2a3b1b2~,FGC43940,NaN,1,0,0,0,0,1
955,AM01358,Y,23141753,A,T,J2a1a1b,AMM342;_PF5163;_Z2222,NaN,0,0,0,5,0,5
956,PF5160,Y,8265737,G,A,J2a1a1b,Z2221,NaN,2,0,0,0,0,2
957,PF5197,Y,19068737,G,A,J2a1a1b1,Z2397,NaN,6,0,0,0,0,6
958,PF5172,Y,7882829,G,A,J2a1a1b1a,NaN,NaN,7,0,0,0,0,7
959,PF5190,Y,17873156,G,A,J2a1a1b1a,NaN,NaN,4,0,0,0,0,4
960,PF4984,Y,21534723,G,A,J2a1a~,NaN,NaN,3,0,0,0,0,3
961,PF5090,Y,8678907,C,T,J2a1a~,NaN,NaN,0,0,0,1,0,1
962,PF4899,Y,8827398,A,T,J2a~,NaN,NaN,0,0,0,1,0,1
963,PF4928,Y,21553644,G,A,J2a~,NaN,NaN,4,0,0,0,0,4
964,PF4957,Y,8420738,G,C,J2a~,F1183,NaN,0,5,0,1,0,5
965,PF4962,Y,14628068,T,C,J2a~,F1810,NaN,0,7,0,1,1,7
966,Z7760,Y,16739675,C,T,J2a~,FGC2795,NaN,0,0,0,1,0,1
967,Z604,Y,16725162,C,T,J2b2a~,AM01366,NaN,0,0,0,1,0,1
968,PF5100,Y,17614366,G,A,J_(Notes),CTS7683;_P354,NaN,10,0,0,0,0,10
969,Z20369^,Y,9457920,C,T,L1a1,NaN,NaN,0,0,0,1,0,1
970,M2476,Y,14472683,G,A,L1a2,NaN,NaN,1,0,0,0,0,1
971,M5710,Y,16900247,A,G,L1a2,NaN,NaN,0,0,2,0,0,2
972,Z20299^,Y,22181078,C,T,L1a2a1a,NaN,NaN,0,0,0,1,0,1
973,Z30984,Y,14194554,C,T,M1,NaN,NaN,0,0,0,1,0,1
974,Z30926,Y,7992575,C,T,M1,NaN,NaN,0,0,0,1,0,1
975,Z4846^,Y,7855600,T,C,N1a1a1a1a,M2208^,NaN,0,1,0,0,0,1
976,Z35264,Y,15238418,G,A,N1a1a1a1a1a2a1a2b1~,NaN,NaN,1,0,0,0,0,1
977,CTS9460,Y,18907504,G,A,N1a1a1a1a2a1a1a1a1a1a1d~,NaN,NaN,1,0,0,0,0,1
978,Z4878,Y,9915300,G,A,N1a1a1a1a2a1a1a1b,NaN,NaN,1,0,0,0,0,1
979,YP5796,Y,17431587,T,G,N1a1a3~,NaN,NaN,0,0,1,0,0,1

In [ ]:
s = "J2a1a1b1a"
mismatch_path(s, df_ch).sort_values(by="Subgroup Name")[-50:]

In [14]:
df_ch[df_ch["Subgroup Name"]=="J"]

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
588,CTS4204,Y,15476324,G,A,J,PF4545;_YSC0001278,NaN,0,0,1,0,1,0
872,F2769,Y,18552360,G,C,J,PF4576,NaN,0,0,1,0,1,0
1216,CTS11571,Y,23163701,C,A,J,PF4617,NaN,0,1,0,0,1,0
1230,PF4620,Y,23255729,A,T,J,CTS11765,NaN,1,0,0,0,1,0

In [217]:
df_der[df_der["Subgroup Name"]=="R1b1a1b1a1a1c2f~"]

Empty DataFrame
Columns: [Name, chrom, pos, ref, alt, Subgroup Name, Alternate Names, rs numbers, A, C, G, T, ref#, alt#]
Index: []

In [39]:
%%time
path_bam = bam_dict["DGB027"]

df_ch, df_der = call_y_bam(df=df, 
                           path_bam=path_bam) #A55903 and A55904

Average Coverage: 0.1696x
#Sites covered: 9976/73148
#Derived Loci:
409 / 9976 covered>0
CPU times: user 59.5 ms, sys: 26.2 ms, total: 85.7 ms
Wall time: 495 ms

In [47]:
df_der[-100:-50]

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
309,Z2823,Y,18387563,G,T,I1,NaN,NaN,0,0,0,1,0,1
310,Z2775,Y,15631787,G,C,I1,CTS4400,NaN,0,1,0,0,0,1
311,Z2774,Y,15599575,G,C,I1,CTS4344,NaN,0,1,0,0,0,1
312,CTS4295,Y,15553583,C,T,I1,Z2771,NaN,0,0,0,1,0,1
313,M253,Y,15022707,C,T,I1,NaN,NaN,0,0,0,1,0,1
314,Z2762,Y,14782128,T,A,I1,CTS3268,NaN,2,0,0,0,0,2
315,Z2757,Y,14402997,G,A,I1,CTS2644,NaN,1,0,0,0,0,1
316,FGC2433,Y,13669371,G,A,I1,NaN,NaN,1,0,0,0,0,1
317,Z2744,Y,13237053,G,A,I1,NaN,NaN,1,0,0,0,0,1
318,Z2733,Y,9148209,C,T,I1,NaN,NaN,0,0,0,1,0,1
319,Z2731,Y,8851406,G,A,I1,NaN,NaN,1,0,0,0,0,1
320,Z2730^,Y,8820460,A,G,I1,NaN,NaN,0,0,2,0,0,2
321,Z2727,Y,8554437,C,T,I1,NaN,NaN,0,0,0,1,0,1
322,Z2724,Y,8274659,C,G,I1,V1771,NaN,0,0,2,0,0,2
323,Z2723,Y,8103323,C,T,I1,NaN,NaN,0,0,0,1,0,1
324,Z2719,Y,7888014,C,T,I1,NaN,NaN,0,0,0,1,0,1
325,Z2717,Y,7774013,A,G,I1,V1423,NaN,0,0,1,0,0,1
326,FGC2422,Y,7749007,C,T,I1,Z2715,NaN,0,0,0,2,0,2
327,FGC2427^,Y,7737070,C,A,I1,Z2713^,NaN,1,0,0,0,0,1
328,Z2711,Y,7649447,C,A,I1,FGC2439,NaN,2,0,0,0,0,2
329,Z2705,Y,7066305,C,T,I1,CTS883,NaN,0,0,0,1,0,1
330,Z2699,Y,6681979,A,C,I1,FGC2430,NaN,0,1,0,0,0,1
331,Y1863,Y,6677619,T,G,I1,FGC2426;_S107,NaN,0,0,1,0,0,1
332,Z2680^,Y,2812119,A,G,I1,CTS209^;_V1092^,NaN,0,0,1,0,0,1
333,Z2785,Y,16084583,G,C,I1,CTS5247,NaN,0,1,0,0,0,1
334,S62,Y,16377198,A,G,I1,L121,NaN,0,0,2,0,0,2
335,Z2750^,Y,14049684,C,T,I1,CTS1755^,NaN,0,0,0,2,0,2
336,L118,Y,15500110,A,C,I1,NaN,NaN,0,1,0,0,0,1
337,Z2817,Y,17886663,C,T,I1,CTS8224,NaN,0,0,0,1,0,1
338,CTS7949^,Y,17758299,C,T,I1,Z2814^,NaN,0,0,0,1,0,1
339,Z2794,Y,16599292,G,A,I1,CTS5993,NaN,1,0,0,0,0,1
340,S63,Y,16478520,A,G,I1,CTS5783,NaN,0,0,1,0,0,1
341,Z2806,Y,17098275,T,C,I1,CTS6765,NaN,0,1,0,0,0,1
342,L123,Y,16693257,C,T,I1,NaN,NaN,0,0,0,1,0,1
343,CTS6629,Y,17019374,T,A,I1,Z2805,NaN,1,0,0,0,0,1
344,CTS6395,Y,16869992,G,A,I1,Z2803,NaN,1,0,0,0,0,1
345,CTS6221^,Y,16737336,G,T,I1,Z2802^,NaN,0,0,0,1,0,1
346,M2623,Y,21529631,G,A,I1a1b1a4a1a1b2~,NaN,NaN,1,0,0,0,0,1
347,Y19917,Y,17349995,G,A,I1a1b1a4a2a1a1b~,NaN,NaN,1,0,0,0,0,1
348,Z59,Y,16802360,G,T,I1a2a,S246,NaN,0,0,0,1,0,1
349,FGC7747,Y,13676296,T,G,I1~,NaN,NaN,0,0,1,0,0,1
350,FGC10273,Y,13669809,T,A,I1~,NaN,NaN,1,0,0,0,0,1
351,Z26579,Y,6927024,G,A,I2a1a1a1a1a1a1c2~,Y3956,NaN,1,0,0,0,0,1
352,Z26650,Y,18184988,C,T,I2a1a1a1a1a1a1d1~,NaN,NaN,0,0,0,1,0,1
353,Y6024,Y,14396927,T,G,I2a1b1a1a1b1a~,FGC35437,NaN,0,0,1,0,0,1
354,Y8549,Y,8470433,G,T,I2a1b1a2a2a1~,NaN,NaN,0,0,0,1,0,1
355,Y16460,Y,16816989,G,A,I2a1b1a2b1a2a1a1a1a3a2~,NaN,NaN,1,0,0,0,0,1
356,Y30846,Y,8614375,C,T,I2a1b1a2b2b~,NaN,NaN,0,1,0,2,1,2
357,S10898,Y,7963379,C,T,I2a1b1b~,NaN,NaN,0,0,0,1,0,1
358,CTS429,Y,6746886,G,A,I2a1b1~,NaN,NaN,1,0,0,0,0,1

In [16]:
dft = df_ch[df_ch["Subgroup Name"].str[0]=="O"]

der = np.sum(dft["alt#"])
ref = np.sum(dft["ref#"])
print((ref,der))
print(f"Error rate: {der/(ref+der)*100:.4g}%")

(np.int64(3076), np.int64(72))
Error rate: 2.287%

In [ ]:
mismatch_path("I1a2a", df_ch).sort_values(by="Subgroup Name")[-50:] # Y2963

# Run Pulldown on custom .bam

In [ ]:
!samtools index

In [46]:
%%time
#path_bam = "/mnt/archgen/Autorun/Results/Human_Shotgun/250206_LH00454_0087_A22H7WLLT4/PTN113.A0101.SG1.3/out.bam"
#path_bam = "/mnt/archgen/Autorun_eager/eager_outputs/SG/PTN/PTN222/merged_bams/initial/PTN222_ss_udghalf_libmerged_rmdup.bam"
path_bam = "/mnt/archgen/Autorun_eager/eager_outputs/SG/PTN/PTN298/trimmed_bam/PTN298_ss.A0101_udghalf.trimmed.bam"
#path_bam = "/mnt/archgen/Autorun_eager/eager_outputs/SG/PTN/PTN167/merged_bams/initial/PTN167_ss_udghalf_libmerged_rmdup.bam"

df_ch, df_der = call_y_bam(df=df, snip5=2, snip3=2,
                           path_bam=path_bam) #A55903 and A55904

Average Coverage: 0.4866x
#Sites covered: 27656/73148
#Derived Loci:
507 / 27656 covered>0
CPU times: user 104 ms, sys: 38.9 ms, total: 143 ms
Wall time: 1.37 s

In [50]:
df_der[-50:]

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
457,Y29666,Y,23314202,G,A,I2a1b1a2b1a2a1a1a1a1a2a1~,NaN,NaN,1,0,0,0,0,1
458,BY44679,Y,17806705,C,T,I2a1b2a2a2b,NaN,NaN,0,0,0,1,0,1
459,L1251.1,Y,2888598,C,T,I2a2a1a,NaN,NaN,0,0,0,1,0,1
460,Y16675,Y,23646509,G,A,I2a2b,NaN,NaN,1,0,0,0,0,1
461,PF3845,Y,23287283,G,T,I2~,CTS11806;_Z2672,NaN,0,0,0,1,0,1
462,Z2665,Y,21585551,A,G,I2~,PF3810,NaN,0,0,1,0,0,1
463,PF3535,Y,14031334,T,A,IJ,M429;_P125,NaN,1,0,0,0,0,1
464,PF3562,Y,21461202,G,A,IJ,NaN,NaN,1,0,0,0,0,1
465,F1460,Y,8906357,C,T,IJ,NaN,NaN,0,0,0,2,0,2
466,CTS10200,Y,19324937,G,A,IJ,NaN,NaN,2,0,0,0,0,2
467,FGC1582,Y,7923823,C,T,IJ,Y1867,NaN,0,0,0,1,0,1
468,FGC1564,Y,7694266,G,A,IJ,YSC0000070,NaN,1,0,0,0,0,1
469,FGC1569,Y,10002861,G,T,IJ,NaN,NaN,0,0,0,1,0,1
470,P126,Y,21225770,C,G,IJ,FGC1566,NaN,0,0,1,0,0,1
471,F2345,Y,16966024,T,C,IJ,FGC1577,NaN,0,1,0,0,0,1
472,CTS6101,Y,16674560,A,G,IJ,Y1889,NaN,0,0,1,0,0,1
473,PF3568,Y,24426007,C,T,IJ,F3629,NaN,0,0,0,1,0,1
474,F4188,Y,15554989,A,G,IJ,PF3539;_V3028,NaN,0,0,2,0,0,2
475,FGC1574,Y,13676377,G,T,IJ,NaN,NaN,0,0,0,1,0,1
476,F2366,Y,17040447,C,A,IJ,FGC1584,NaN,1,0,0,0,0,1
477,F3402,Y,23069523,A,G,IJ,S2,NaN,0,0,1,0,0,1
478,CTS6932,Y,17200869,G,A,IJ,FGC1565,NaN,2,0,0,0,0,2
479,L748,Y,17012180,C,A,IJ,PF3546;_YSC0000289,NaN,1,0,0,0,0,1
480,ZS9899,Y,23265541,G,T,J1a2a1a1a~,NaN,NaN,0,0,0,1,0,1
481,ZS372,Y,7559119,C,T,J1a2a1a2d2b1~,NaN,NaN,0,0,0,1,0,1
482,FGC8227,Y,22208651,G,A,J1a2a1a2d2b2b2c4b1b2~,NaN,NaN,1,0,0,0,0,1
483,Y27529,Y,15729142,A,G,J1a2a1a2d2b2b2c4d2a2a5a1a~,NaN,NaN,0,0,1,0,0,1
484,FGC5464,Y,18594912,C,T,J1a2a1a2d2b2b2c4d2a2a5a1e4a6k2b1~,NaN,NaN,0,0,0,1,0,1
485,CTS9538,Y,18952077,G,A,J2a,PF4919,NaN,1,0,0,0,0,1
486,CTS3810,Y,15197944,G,A,J2b1,NaN,NaN,1,0,0,0,0,1
487,Z20613,Y,17499024,C,T,L2~,NaN,NaN,0,0,0,1,0,1
488,Z4846^,Y,7855600,T,C,N1a1a1a1a,M2208^,NaN,0,1,0,0,0,1
489,YP5796,Y,17431587,T,G,N1a1a3~,NaN,NaN,0,0,1,0,0,1
490,MF14236,Y,6738624,T,C,O1b1a1a1a1b1a1a2b1,NaN,NaN,0,2,0,0,0,2
491,Z39488,Y,21595529,C,T,O1b1a1a1b1b,NaN,NaN,0,0,0,1,0,1
492,F2770,Y,18552726,C,T,O2a1b1a1a1a1a1a1b1f,NaN,NaN,0,0,0,1,0,1
493,F3042,Y,19407407,T,C,O2a1b1a1a1a1g,NaN,NaN,0,1,0,0,0,1
494,Y30494,Y,16242725,G,A,O2a2b1a2a1a4a1a,NaN,NaN,1,0,0,0,0,1
495,PF1337.2,Y,28790215,G,C,Q1b1a1a1g~,NaN,NaN,0,1,0,0,0,1
496,Z19376^,Y,8411111,C,T,Q1b1a1a1j1,NaN,NaN,0,0,0,1,0,1
497,BZ285,Y,22935337,G,A,Q2a1a2c1a2~,NaN,NaN,1,0,0,0,0,1
498,Y2986,Y,7929100,C,A,Q2a1c1a,FGC4872,NaN,1,0,0,0,0,1
499,L68.2,Y,18700150,C,T,Q2b,PF3781.2;_S329.2,rs35547782,0,0,0,1,0,1
500,SRY10831.2,Y,2657176,T,C,R1a1,Page65;_PF6234;_SRY1532,NaN,0,1,0,0,0,1
501,YP5024,Y,8561200,C,T,R1a2a~,NaN,NaN,0,0,0,1,0,1
502,L132.2,Y,17464197,T,C,R1b1a1b1a1a1c1a2a1~,NaN,NaN,0,1,0,0,0,1
503,FGC453,Y,15719082,G,A,R1b1a1b1a1a2c1a1a1a1a1c1,S566,NaN,1,0,0,0,0,1
504,BY18891,Y,18719201,G,A,R1b1a1b1a1a2c1a5c3d,NaN,NaN,1,0,0,0,0,1
505,SK2055,Y,22732394,G,A,R1b2b1,NaN,NaN,2,0,0,0,0,2
506,Z41509,Y,6859717,C,T,S1a1b1d2a~,NaN,NaN,0,0,0,1,0,1

In [30]:
dft = df_ch[df_ch["Subgroup Name"].str[0]=="J"]

der = np.sum(dft["alt#"])
ref = np.sum(dft["ref#"])
print((ref,der))
print(f"Error rate: {der/(ref+der)*100:.4g}%")

(np.int64(1320), np.int64(1))
Error rate: 0.0757%

In [28]:
dft = df_ch[df_ch["Subgroup Name"].str[0]=="J"]

der = np.sum(dft["alt#"])
ref = np.sum(dft["ref#"])
print((ref,der))
print(f"Error rate: {der/(ref+der)*100:.4g}%")

(np.int64(1455), np.int64(10))
Error rate: 0.6826%

In [ ]:
#E1b1b1a1b1a6a1 #PTN222
#I2a1a2b1a1a1 #PTN298

In [51]:
mismatch_path("I2a1a2b1a1a1", df_ch).sort_values(by="Subgroup Name")[-100:-50]

Mismatches: 0 / 116

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
16570,CTS7469,Y,17497181,C,A,I,NaN,NaN,2,0,0,0,0,2
16620,PF3760,Y,17511797,A,G,I,CTS7502,NaN,0,0,1,0,0,1
16658,PF3761,Y,17525137,A,G,I,CTS7540,NaN,0,0,1,0,0,1
25934,CTS11540,Y,23156725,C,T,I,PF3842,NaN,0,0,0,1,0,1
24551,PF3837,Y,22573702,G,A,I,NaN,NaN,3,0,0,0,0,3
24417,PF3836,Y,22525421,T,G,I,NaN,NaN,0,0,2,0,0,2
23417,PF3815,Y,21841289,G,T,I,NaN,NaN,0,0,0,1,0,1
22735,PF3809,Y,21556106,G,A,I,NaN,NaN,2,0,0,0,0,2
22686,PF3807,Y,21535086,G,A,I,NaN,NaN,1,0,0,0,0,1
22228,L503,Y,21359407,C,G,I,NaN,NaN,0,0,2,0,0,2
21618,PH3797,Y,21130059,A,G,I,NaN,NaN,0,0,1,0,0,1
21602,PF3796,Y,21119888,G,T,I,NaN,NaN,0,0,0,1,0,1
20121,PF3790,Y,19104986,G,A,I,CTS9860,NaN,1,0,0,0,0,1
19947,L41,Y,19048602,G,A,I,PF3787,NaN,1,0,0,0,0,1
19831,CTS9618,Y,18992894,T,C,I,PF3786;_V3671,NaN,0,1,0,0,0,1
18151,PF3775,Y,18078759,T,A,I,CTS8545,NaN,1,0,0,0,0,1
17764,PF3771,Y,17940414,G,A,I,CTS8333,NaN,1,0,0,0,0,1
17451,PF3768,Y,17818847,G,A,I,CTS8064,NaN,2,0,0,0,0,2
9590,PF3706,Y,14337364,T,C,I,CTS2514,NaN,0,1,0,0,0,1
9413,CTS2387,Y,14286853,T,C,I,PF3705,NaN,0,1,0,0,0,1
13842,PF3742,Y,16354708,G,A,I,U179,NaN,1,0,0,0,0,1
5691,L755,Y,8465165,C,T,I,PF3659;_YSC0000283,NaN,0,0,0,2,0,2
1883,CTS674,Y,6943522,C,T,I,FI1;_PF3630,NaN,0,0,0,1,0,1
2348,CTS1006,Y,7137088,C,T,I,NaN,NaN,0,0,0,1,0,1
2592,M11064,Y,7244075,A,G,I,PF3634,NaN,0,0,1,0,0,1
8730,PF3699,Y,14073053,G,A,I,CTS1800,NaN,2,0,0,0,0,2
3649,PF3642,Y,7712917,A,T,I,NaN,NaN,0,0,0,1,0,1
5824,PF3661,Y,8484606,C,A,I,V2111,NaN,2,0,0,0,0,2
6005,L758,Y,8536868,C,G,I,PF3663;_V2199;_YSC0000285,NaN,0,0,1,0,0,1
8329,FGC2415,Y,13835003,T,C,I,Y1880,NaN,0,1,0,0,0,1
7221,PF3672,Y,9376351,T,C,I,NaN,NaN,0,1,0,0,0,1
7665,PF3677,Y,9891668,G,A,I,NaN,NaN,2,0,0,0,0,2
966,PF3626,Y,6652911,T,C,I2,Z2632,NaN,0,2,0,0,0,2
23083,PF3812,Y,21709779,G,A,I2,Z2666,NaN,1,0,0,0,0,1
20809,Z2661,Y,19347315,T,C,I2,CTS10247;_PF3792,NaN,0,1,0,0,0,1
16743,CTS7605,Y,17559790,G,A,I2,PF3764;_Z2656,NaN,1,0,0,0,0,1
14540,P215,Y,16638804,A,G,I2,M438;_PF3853;_S31,NaN,0,0,1,0,0,1
9134,Z2646,Y,14202119,C,A,I2,CTS2159;_PF3702,NaN,1,0,0,0,0,1
12611,Z2652,Y,15718964,G,A,I2,CTS4568;_PF3733,NaN,1,0,0,0,0,1
11743,Z2650,Y,15349855,G,A,I2a,CTS4039;_PF3723,NaN,1,0,0,0,0,1
11753,CTS4047,Y,15354989,G,A,I2a,PF3724,NaN,1,0,0,0,0,1
12685,S2672,Y,15745246,T,A,I2a1a,CTS4643;_PF4011;_Z2619,NaN,1,0,0,0,0,1
2351,CTS1007,Y,7137277,G,A,I2a1a,AM00530;_PF3955,NaN,1,0,0,0,0,1
2748,PF3959,Y,7307576,C,T,I2a1a,AM00531;_CTS1279;_Z2610,NaN,0,0,0,1,0,1
1196,CTS410,Y,6732120,C,T,I2a1a,AM00529;_PF3949;_S2626;_Z2609,NaN,0,0,0,1,0,1
4562,PF3967,Y,8056732,A,T,I2a1a,Z2614,NaN,0,0,0,1,0,1
16412,Z2622,Y,17427444,A,T,I2a1a,AM00523;_CTS7335;_PF4023,NaN,0,0,0,1,0,1
4252,PF3966,Y,7919987,C,G,I2a1a,Z2612,NaN,0,0,1,0,0,1
9674,CTS2580,Y,14371245,T,C,I2a1a,AM00518;_PF4003;_S2648,NaN,0,1,0,0,0,1
13226,AM00521,Y,15984708,C,T,I2a1a,CTS5044;_PF4012;_Z2620,NaN,0,0,0,1,0,1

## Test on 16x PTN016 sample

In [46]:
%%time
path_bam = "/mnt/archgen/Autorun_eager/eager_outputs/SG/PTN/PTN016/trimmed_bam/PTN016_ss.A0101_udgnone.trimmed.bam"



df_ch, df_der = call_y_bam(df=df, 
                           path_bam=path_bam) #A55903 and A55904

Average Coverage: 7.6752x
#Sites covered: 71913/73148
#Derived Loci:
1279 / 71913 covered>0
CPU times: user 299 ms, sys: 0 ns, total: 299 ms
Wall time: 6.21 s

In [ ]:
df_der[-40:]

In [ ]:
s = "G2a2b2a1a1b1a1a1a1b1"
mismatch_path(s, df_ch).sort_values(by="Subgroup Name")[-50:]

In [34]:
dft = df_ch[df_ch["Subgroup Name"].str[0]=="J"]

der = np.sum(dft["alt#"])
ref = np.sum(dft["ref#"])
print((ref,der))
print(f"Error rate: {der/(ref+der)*100:.4g}%")

(45708, 497)
Error rate: 1.076%

### Bam from Autorun (Pandora Path)

In [120]:
%%time

#path_bam = "/mnt/archgen/Autorun/Results/Human_RM/250214_LH00454_0091_B22TCLKLT3/WIT004.A0101.RM1.1/out.bam"
path_bam = "/mnt/archgen/Autorun/Results/Human_RM/250214_LH00454_0091_B22TCLKLT3/WIT005.A0101.RM1.1/out.bam"

df_ch, df_der = call_y_bam(df=df, 
                           path_bam=path_bam) #A55903 and A55904

Average Coverage: 12.5988x
#Sites covered: 52088/73148
#Derived Loci:
1204 / 52088 covered>0
CPU times: user 174 ms, sys: 0 ns, total: 174 ms
Wall time: 2.38 s

In [ ]:
df_der[-50:]

In [ ]:
R1b1a1b1a1a1c
R1b1a1b1a1a1c1a2a1

In [119]:
mismatch_path("R1a", df_ch).sort_values(by="Subgroup Name")[-50:]

Mismatches: 2 / 2

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
59,PF6111,Y,7132713,G,A,R1,CTS997;_M612,NaN,0,0,1,0,1,0
270,M662,Y,14336840,C,T,R1a~,F1769;_PF6179,NaN,0,156,0,0,156,0

In [26]:
%%time

path_bam = "/mnt/archgen/Autorun/Results/Human_Shotgun/250318_LH00454_0096_B22YH7VLT3/BMG001.A0101.SG1.1/out.bam"

df_ch, df_der = call_y_bam(df=df, 
                           path_bam=path_bam) #A55903 and A55904

Average Coverage: 0.0112x
#Sites covered: 779/73148
#Derived Loci:
18 / 779 covered>0
CPU times: user 40.5 ms, sys: 24.9 ms, total: 65.4 ms
Wall time: 341 ms

In [ ]:
df_der

In [19]:
s = "R1b1a1"
mismatch_path(s, df_ch).sort_values(by="Subgroup Name")[-50:]

Mismatches: 0 / 2

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
334,Page37,Y,15581983,A,G,R,M207;_UTY2,NaN,0,0,1,0,0,1
619,PF6498,Y,21312064,C,A,R1b1a1,NaN,NaN,1,0,0,0,0,1

In [99]:
%%time
iid = "KKH004"
path_bam = f"/mnt/archgen/Autorun_eager/eager_outputs/SG/{iid[:3]}/{iid}/trimmed_bam/{iid}_ss.A0101_udghalf.trimmed.bam"

df_ch, df_der = call_y_bam(df=df, 
                           path_bam=path_bam) #A55903 and A55904

Average Coverage: 0.4336x
#Sites covered: 24552/73148
#Derived Loci:
516 / 24552 covered>0
CPU times: user 84.9 ms, sys: 32.4 ms, total: 117 ms
Wall time: 1.28 s

In [102]:
df_t = df_ch[df_ch["Subgroup Name"].str[0]=="I"]
refs = np.sum(df_t["ref#"])
alts = np.sum(df_t["alt#"])

frac = alts / (refs + alts)
print(f"Error Rate: {frac:.6f} ")

Error Rate: 0.045534

In [107]:
df_der[-100:-50]

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
416,FGC2427^,Y,7737070,C,A,I1,Z2713^,NaN,4,0,0,0,0,4
417,FGC2425,Y,7742116,T,A,I1,Z2714,NaN,1,0,0,0,0,1
418,FGC2422,Y,7749007,C,T,I1,Z2715,NaN,0,0,0,1,0,1
419,YSC0000301,Y,23580442,T,C,I1,Z2882,NaN,0,1,0,0,0,1
420,CTS11552,Y,23159643,C,A,I1,Z2872,NaN,1,0,0,0,0,1
421,Z2717,Y,7774013,A,G,I1,V1423,NaN,0,0,1,0,0,1
422,Z2823,Y,18387563,G,T,I1,NaN,NaN,0,0,0,1,0,1
423,CTS11503^,Y,23142317,C,G,I1,Z2869^,NaN,0,0,1,0,0,1
424,V1427,Y,7776846,T,G,I1,FGC2440;_Y3658,NaN,0,0,1,0,0,1
425,CTS8716^,Y,18160939,C,T,I1,Z2822^,NaN,0,0,0,2,0,2
426,Z2721,Y,8067224,C,T,I1,NaN,NaN,0,0,0,1,0,1
427,Z2866^,Y,22967741,C,G,I1,CTS11126^,NaN,0,0,1,0,0,1
428,S66,Y,22914378,T,C,I1,CTS11042,NaN,0,1,0,0,0,1
429,CTS8394,Y,17976203,G,A,I1,Z2818,NaN,1,0,0,0,0,1
430,Z2887,Y,24499543,C,T,I1,NaN,NaN,0,0,0,3,0,3
431,Z2759^,Y,14454653,G,A,I1,CTS2738^,NaN,1,0,0,0,0,1
432,CTS1748,Y,14047137,A,G,I1,Z2749,NaN,0,0,1,0,0,1
433,Z2811,Y,17500131,T,C,I1,CTS7477,NaN,0,1,0,0,0,1
434,Z2776,Y,15686138,A,G,I1,CTS4508,NaN,0,0,1,0,0,1
435,Z2781,Y,15821472,G,T,I1,CTS4790,NaN,0,0,0,1,0,1
436,Z2845,Y,21309376,G,A,I1,S22865,NaN,1,0,0,0,0,1
437,P30,Y,14496753,G,A,I1,NaN,NaN,1,0,0,0,0,1
438,Z2788,Y,16351523,C,T,I1,L495,NaN,0,0,0,2,0,2
439,Z2834,Y,19235426,G,A,I1,CTS10062,NaN,1,0,0,0,0,1
440,Z2789,Y,16392707,G,T,I1,L842;_YSC0000264,NaN,0,0,0,1,0,1
441,CTS7061,Y,17264749,C,T,I1,Z2807,NaN,0,0,0,2,0,2
442,Z2835,Y,19239993,C,T,I1,L759;_YSC0000295,NaN,0,0,0,1,0,1
443,S63,Y,16478520,A,G,I1,CTS5783,NaN,0,0,1,0,0,1
444,YSC0000296^,Y,19273317,T,G,I1,L740^;_V3959^;_Z2836^,NaN,0,0,2,0,0,2
445,Z2794,Y,16599292,G,A,I1,CTS5993,NaN,3,0,0,0,0,3
446,L123,Y,16693257,C,T,I1,NaN,NaN,0,0,0,1,0,1
447,CTS6221^,Y,16737336,G,T,I1,Z2802^,NaN,0,0,0,1,0,1
448,CTS641,Y,6923525,C,T,I1,Z2702,NaN,0,0,0,1,0,1
449,Z2808,Y,17299483,G,A,I1,CTS7121,NaN,2,0,0,0,0,2
450,L118,Y,15500110,A,C,I1,NaN,NaN,0,2,0,0,0,2
451,Z2766,Y,15158740,A,G,I1,CTS3762,NaN,0,0,1,0,0,1
452,CTS1220,Y,7277546,A,G,I1,Z2706,NaN,0,0,1,0,0,1
453,Z2824,Y,18614569,T,A,I1,CTS9010,NaN,1,0,0,0,0,1
454,Z2848,Y,21402851,C,T,I1,NaN,NaN,0,0,0,2,0,2
455,Z2810,Y,17453026,T,G,I1,CTS7386,NaN,0,0,2,0,0,2
456,CTS3506,Y,14981302,A,G,I1,Z2765,NaN,0,0,1,0,0,1
457,Z2764,Y,14955656,C,A,I1,CTS3474;_V2712,NaN,1,0,0,0,0,1
458,Z2849,Y,21406999,C,T,I1,L764;_YSC0000271,NaN,0,0,0,2,0,2
459,FGC2438,Y,6681479,T,G,I1,S108;_Y1864,NaN,0,0,2,0,0,2
460,Z2903,Y,22184102,A,G,I1a2a1a1d,S1948,NaN,0,0,1,0,0,1
461,S19340,Y,17197466,C,A,I1a2a1a1d1b~,NaN,NaN,1,0,0,0,0,1
462,S22055,Y,19281413,G,A,I1a2a1a1d1b~,NaN,NaN,1,0,0,0,0,1
463,CTS9352,Y,18843729,C,A,I1a2a1a1d1~,S2134;_Z2902,NaN,1,0,0,0,0,1
464,Z2898,Y,18921801,G,A,I1a2a1a1d1~,CTS9477;_S2135,NaN,2,0,0,0,0,2
465,Z60,Y,18234588,C,G,I1a2a1a1~,S337,NaN,0,0,1,0,0,1

In [108]:
s = "I1a2a1a1d1b"
mismatch_path(s, df_ch).sort_values(by="Subgroup Name")[-50:]

Mismatches: 1 / 120

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
12682,Z2794,Y,16599292,G,A,I1,CTS5993,NaN,3,0,0,0,0,3
14510,Z2810,Y,17453026,T,G,I1,CTS7386,NaN,0,0,2,0,0,2
7629,Z2750^,Y,14049684,C,T,I1,CTS1755^,NaN,0,0,0,1,0,1
7621,CTS1748,Y,14047137,A,G,I1,Z2749,NaN,0,0,1,0,0,1
7611,CTS1739,Y,14042842,A,G,I1,Z2748,NaN,0,0,1,0,0,1
6912,Z2744,Y,13237053,G,A,I1,NaN,NaN,2,0,0,0,0,2
6899,Z2741^,Y,13221806,T,A,I1,NaN,NaN,2,0,0,0,0,2
6705,Z2738,Y,9885854,A,G,I1,NaN,NaN,0,0,1,0,0,1
6341,Z2733,Y,9148209,C,T,I1,NaN,NaN,0,0,0,1,0,1
6026,Z2730^,Y,8820460,A,G,I1,NaN,NaN,0,0,1,0,0,1
4057,Z2721,Y,8067224,C,T,I1,NaN,NaN,0,0,0,1,0,1
14613,Z2811,Y,17500131,T,C,I1,CTS7477,NaN,0,1,0,0,0,1
3296,V1427,Y,7776846,T,G,I1,FGC2440;_Y3658,NaN,0,0,1,0,0,1
3228,FGC2422,Y,7749007,C,T,I1,Z2715,NaN,0,0,0,1,0,1
3203,FGC2425,Y,7742116,T,A,I1,Z2714,NaN,1,0,0,0,0,1
3189,FGC2427^,Y,7737070,C,A,I1,Z2713^,NaN,4,0,0,0,0,4
2966,FGC2432,Y,7656352,T,G,I1,V1339;_Z2712,NaN,0,0,2,0,0,2
2955,S110,Y,7652844,T,G,I1,L845;_V1333;_YSC0000278,NaN,0,0,1,0,0,1
2494,Z2708,Y,7377905,C,A,I1,CTS1393,NaN,1,0,0,0,0,1
2276,CTS1220,Y,7277546,A,G,I1,Z2706,NaN,0,0,1,0,0,1
1566,CTS641,Y,6923525,C,T,I1,Z2702,NaN,0,0,0,1,0,1
982,FGC2438,Y,6681479,T,G,I1,S108;_Y1864,NaN,0,0,2,0,0,2
3286,Z2717,Y,7774013,A,G,I1,V1423,NaN,0,0,1,0,0,1
8603,Z2759^,Y,14454653,G,A,I1,CTS2738^,NaN,1,0,0,0,0,1
7884,CTS2044,Y,14164159,A,G,I1,AM00084,NaN,0,0,1,0,0,1
12430,S63,Y,16478520,A,G,I1,CTS5783,NaN,0,0,1,0,0,1
14142,Z2808,Y,17299483,G,A,I1,CTS7121,NaN,2,0,0,0,0,2
14064,CTS7061,Y,17264749,C,T,I1,Z2807,NaN,0,0,0,2,0,2
13218,CTS6395,Y,16869992,G,A,I1,Z2803,NaN,1,0,0,0,0,1
12942,CTS6221^,Y,16737336,G,T,I1,Z2802^,NaN,0,0,0,1,0,1
12861,L123,Y,16693257,C,T,I1,NaN,NaN,0,0,0,1,0,1
24149,Z2885,Y,23957372,C,T,I1,NaN,NaN,0,0,0,1,0,1
8680,P30,Y,14496753,G,A,I1,NaN,NaN,1,0,0,0,0,1
12254,Z2789,Y,16392707,G,T,I1,L842;_YSC0000264,NaN,0,0,0,1,0,1
24434,Z2887,Y,24499543,C,T,I1,NaN,NaN,0,0,0,3,0,3
11301,Z2781,Y,15821472,G,T,I1,CTS4790,NaN,0,0,0,1,0,1
10949,Z2776,Y,15686138,A,G,I1,CTS4508,NaN,0,0,1,0,0,1
10562,L118,Y,15500110,A,C,I1,NaN,NaN,0,2,0,0,0,2
9926,Z2766,Y,15158740,A,G,I1,CTS3762,NaN,0,0,1,0,0,1
9565,CTS3506,Y,14981302,A,G,I1,Z2765,NaN,0,0,1,0,0,1
9505,Z2764,Y,14955656,C,A,I1,CTS3474;_V2712,NaN,1,0,0,0,0,1
12158,Z2788,Y,16351523,C,T,I1,L495,NaN,0,0,0,2,0,2
21567,Z2903,Y,22184102,A,G,I1a2a1a1d,S1948,NaN,0,0,1,0,0,1
13934,S19340,Y,17197466,C,A,I1a2a1a1d1b~,NaN,NaN,1,0,0,0,0,1
18210,S22055,Y,19281413,G,A,I1a2a1a1d1b~,NaN,NaN,1,0,0,0,0,1
17364,Z2898,Y,18921801,G,A,I1a2a1a1d1~,CTS9477;_S2135,NaN,2,0,0,0,0,2
17219,CTS9352,Y,18843729,C,A,I1a2a1a1d1~,S2134;_Z2902,NaN,1,0,0,0,0,1
7013,FGC8670,Y,13657312,G,A,I1a2a1a1d~,NaN,NaN,0,0,2,0,2,0
16337,Z60,Y,18234588,C,G,I1a2a1a1~,S337,NaN,0,0,1,0,0,1
17770,V3772,Y,19103066,A,T,I1a~,CTS9857,NaN,0,0,0,1,0,1

# 1) Run Pulldown on Twist test

In [105]:
%%time

iid = "A54927"
#path_bam = f'/mnt/archgen/users/hringbauer/data/twist_test/dedup.q25l35/postdd.twist.c2/{iid}.bam'
path_bam = f'/mnt/archgen/users/hringbauer/data/twist_test/dedup.q25l35/postdd.1240k/{iid}.bam'
!samtools index $path_bam

df_ch, df_der = call_y_bam(df=df, 
                           path_bam=path_bam) #A55903 and A55904

Average Coverage: 0.2718x
#Sites covered: 11862/73148
#Derived Loci:
412 / 11862 covered>0
CPU times: user 100 ms, sys: 52.3 ms, total: 153 ms
Wall time: 3.82 s

In [13]:
df_der[-50:]

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
0,P305,Y,2710154,A,G,A1,NaN,NaN,0,0,1,0,0,1
1,Z17389,Y,24509299,C,T,BT,NaN,NaN,0,0,0,1,0,1
2,M8952,Y,2855637,C,T,BT,NaN,NaN,0,0,0,1,0,1
3,M9030,Y,8596285,G,A,BT,NaN,NaN,1,0,0,0,0,1
4,M9065,Y,9850725,G,C,BT,NaN,NaN,0,2,0,0,0,2
5,Z40391,Y,9850729,G,C,BT,NaN,NaN,0,2,0,0,0,2
6,M9344,Y,21975362,C,A,BT,NaN,NaN,1,0,0,0,0,1
7,PF969,Y,19140679,C,T,BT,M9278,NaN,0,0,0,1,0,1
8,M9282,Y,19207843,C,A,BT,NaN,NaN,1,0,0,0,0,1
9,M9293,Y,19416000,C,G,BT,NaN,NaN,0,0,1,0,0,1
10,PF258,Y,7729324,C,T,CT,M5608,NaN,0,0,0,1,0,1
11,PF815,Y,16844116,G,A,CT,M5706,NaN,1,0,0,0,0,1
12,Z1764,Y,2744983,C,T,E1b1a1a1a2a1a3b1a2a1,CTS127,NaN,0,0,0,1,0,1
13,PF2716,Y,18051289,C,G,F,F2688;_M3722,NaN,0,0,1,0,0,1
14,Y19068,Y,17133905,C,T,I2a1a1b1c~,NaN,NaN,0,0,0,2,0,2
15,PF5991,Y,2686727,G,A,P1_or_K2b2a,F4;_M1183,rs67960559,1,0,0,0,0,1
16,Page37,Y,15581983,A,G,R,M207;_UTY2,NaN,0,0,1,0,0,1
17,PF6498,Y,21312064,C,A,R1b1a1,NaN,NaN,1,0,0,0,0,1

In [18]:
df_t = df_ch[df_ch["Subgroup Name"].str[0]=="E"]
refs = np.sum(df_t["ref#"])
alts = np.sum(df_t["alt#"])

frac = alts / (refs + alts)
print(f"Error Rate: {frac:.6f} ")

Error Rate: 0.011364

# 2) Run Brienzi aDNA
Here: Use the Brienzi Y capture

In [12]:
%%time
df_ch, df_der = call_y_bam(df=df, 
                           path_bam="/mnt/archgen/users/hringbauer/data/brienziYcapture/A55903.bam") #A55903 and A55904

Average Coverage: 15.7615x
#Sites covered: 60398/73148
#Derived Loci:
1049 / 60398 covered>0
CPU times: user 243 ms, sys: 59.2 ms, total: 302 ms
Wall time: 6.62 s

In [ ]:
### Browse the results - update the output index to "browse". The derived SNPs at the end are the most interesting
df_der[-50:]

In [154]:
%%time
df_ch, df_der = call_y_bam(df=df, 
                           path_bam="/mnt/archgen/users/hringbauer/data/brienziYcapture/A55904.bam")

Average Coverage: 13.0144x
#Sites covered: 58128/73148
#Derived Loci:
998 / 58128 covered>0
CPU times: user 210 ms, sys: 58.7 ms, total: 269 ms
Wall time: 5.79 s

In [ ]:
df_der[-50:]

In [68]:
df_ch[df_ch["Subgroup Name"]=="G2a2b2a1a1c1a1"]

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
617,Z3388,Y,18396357,C,T,G2a2b2a1a1c1a1,NaN,rs936457912,0,0,0,1,0,1

# Run Single Target Individual
Fill in the indivdiual of your choice

In [316]:
iid = "THE006"
bam_dict[iid]

'/mnt/archgen/Autorun_eager/eager_outputs/TF/THE/THE006/merged_bams/initial/THE006_ss_udgnone_libmerged_rmdup.bam'

In [ ]:
iid = "LDH"

In [58]:
%%time

df_ch, df_der = call_y_bam(df=df, 
                           path_bam="/mnt/archgen/Autorun_eager/eager_outputs/SG/LDH/LDH086/trimmed_bam/LDH086_ss.A0101_udgnone.trimmed.bam",
                           path_temp='/mnt/archgen/users/hringbauer/git/y_chrom/temp/temp.tsv')

Average Coverage: 0.2502x
#Sites covered: 15813/73148
#Derived Loci:
493 / 15813 covered>0
CPU times: user 84 ms, sys: 43.6 ms, total: 128 ms
Wall time: 3.12 s

In [63]:
df_der[-200:-150]

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
293,PF2883,Y,8427005,A,G,G2,F1189;_M3267,rs563631868,0,0,1,0,0,1
294,PF2887,Y,8545324,T,A,G2,F1294;_M3484,rs574354813,1,0,0,0,0,1
295,M3320,Y,16262350,C,T,G2a,CTS5416,rs571028221,0,0,0,2,0,2
296,M3401,Y,21760742,C,T,G2a,PF3066,rs566883997,0,0,0,1,0,1
297,CTS211,Y,2812741,C,T,G2a,M3227;_PF2783,rs574877355,0,0,0,2,0,2
298,PF2994,Y,16861108,G,A,G2a,F2301;_M3335,rs528076051,1,0,0,0,0,1
299,CTS9318,Y,18819146,T,A,G2a,M3362;_PF3026,rs540494999,1,0,0,0,0,1
300,PF2972,Y,15660640,C,T,G2a,F1980;_M3309,rs549001775,0,0,0,1,0,1
301,PF3141,Y,23973594,T,G,G2a,U5,rs2178500,0,0,1,0,0,1
302,FGC739,Y,18701589,C,T,G2a1a,Z6698,rs774311179,0,0,0,1,0,1
303,Z6675,Y,14513425,C,T,G2a1a1a,FGC708,rs1017367909,0,0,0,1,0,1
304,BY190025,Y,8032288,G,A,G2a1a1a1a1a3~,NaN,NaN,1,0,0,0,0,1
305,L1259,Y,15615340,C,G,G2a2,CTS4367;_M3308;_PF2970,rs561766566,0,0,1,0,0,1
306,FGC58149,Y,15776365,C,G,G2a2a1a1~,NaN,NaN,0,0,1,0,0,1
307,FGC50766,Y,23249089,G,A,G2a2a1a2a1a1b1b~,NaN,NaN,1,0,0,0,0,1
308,FT1923,Y,16297272,C,T,G2a2a1a2a1a1b3~,NaN,NaN,0,0,0,1,0,1
309,FT99172,Y,8016260,G,A,G2a2a1a2a2a1b1~,NaN,rs1034077808,1,0,0,0,0,1
310,Z42577,Y,19129810,G,A,G2a2a1a2b,NaN,NaN,1,0,0,0,0,1
311,FGC34436,Y,9643279,G,A,G2a2a1b,NaN,NaN,1,0,0,0,0,1
312,BY202517,Y,7054557,C,T,G2a2a2a3~,NaN,NaN,0,0,0,1,0,1
313,Y112444,Y,23854825,G,A,G2a2a2b1,NaN,NaN,1,0,0,0,0,1
314,S148,Y,14692227,T,C,G2a2b,L32;_PF3266;_U8,rs7892988,0,1,0,0,0,1
315,L190,Y,18759690,C,T,G2a2b,M485,rs564870050,0,0,0,1,0,1
316,L30,Y,15604899,C,T,G2a2b,PF3267;_S126,rs34134567,0,0,0,2,0,2
317,M3352,Y,17787465,A,T,G2a2b,CTS7992,rs562451324,0,0,0,1,0,1
318,PF3254,Y,6425529,C,A,G2a2b,NaN,rs866411369,2,0,0,0,0,2
319,M3370,Y,19060222,T,G,G2a2b,CTS9763;_PF3271,rs545137085,0,0,1,0,0,1
320,F3139,Y,21151007,T,C,G2a2b,PF3274,rs780646639,0,1,0,0,0,1
321,M3418,Y,22903313,C,A,G2a2b1,S24848,rs575838386,1,0,0,0,0,1
322,PF3319,Y,23327970,G,A,G2a2b1,M3423,rs575331280,2,0,0,0,0,2
323,M3315,Y,15752816,G,T,G2a2b1,NaN,rs574356875,0,0,0,1,0,1
324,S25566,Y,23431153,A,G,G2a2b1,M3427,rs547307672,0,0,1,0,0,1
325,M3281,Y,14002366,G,A,G2a2b1,PF3297,rs549191151,1,0,0,0,0,1
326,M3372,Y,19087143,C,T,G2a2b1,M461,rs547345637,0,0,0,1,0,1
327,S23266,Y,21562442,G,A,G2a2b1,M9330,rs754187996,1,0,0,0,0,1
328,PF3307,Y,17246670,T,C,G2a2b1,M3344,rs530109689,0,2,0,0,0,2
329,M3426,Y,23394892,T,G,G2a2b1a,S25516,rs564471781,0,0,1,0,0,1
330,M3354,Y,17843613,G,A,G2a2b1a,S20284,rs531274744,1,0,0,0,0,1
331,M3292,Y,14323491,T,C,G2a2b1a,S15820,rs556480164,0,1,0,0,0,1
332,M3302,Y,15104273,T,G,G2a2b1a2,NaN,rs576974702,0,0,1,0,0,1
333,M3337,Y,16907941,C,T,G2a2b1a2,NaN,rs569270020,0,0,0,1,0,1
334,M3346,Y,17460050,G,T,G2a2b1a2,NaN,rs551970684,0,0,0,1,0,1
335,BY81132,Y,9811468,C,T,G2a2b1a2a2~,NaN,NaN,0,0,0,1,0,1
336,BY207948,Y,16945373,C,A,G2a2b1b1a1b1a1b~,NaN,NaN,1,0,0,0,0,1
337,Z6352,Y,15024143,C,T,G2a2b1b1a1c1,NaN,rs962754136,0,0,0,1,0,1
338,Z46343,Y,8729974,G,A,G2a2b1b1a1c1a~,BY74400,NaN,1,0,0,0,0,1
339,FT102048,Y,16197743,C,T,G2a2b1b1b~,NaN,NaN,0,0,0,1,0,1
340,ZS669.2,Y,8383185,G,A,G2a2b2a1a1a1a1a1a1a1a1a10,NaN,rs759844852,1,0,0,0,0,1
341,Z31375,Y,8573806,G,A,G2a2b2a1a1a1a1a1a1a4~,NaN,NaN,1,0,0,0,0,1
342,FGC986,Y,14249491,C,T,G2a2b2a1a1a1a1a1a3~,NaN,NaN,0,0,0,1,0,1

In [60]:
df_der["Subgroup Name"].str[:2].value_counts()

Subgroup Name
G2    86
BT    74
G     41
A0    38
CT    38
E1    25
R1    24
I2    19
F     16
A1    12
J1    12
C1    12
C2     9
Q2     8
I1     7
O2     6
Q1     6
J2     6
N1     5
G1     4
S1     4
B2     4
D1     4
T1     3
L1     3
H1     3
O1     2
M1     2
B3     2
S4     2
E2     2
S2     2
H2     2
D2     2
CF     1
C      1
K2     1
J      1
L2     1
N      1
R      1
T      1
Name: count, dtype: int64

In [64]:
df_ch[df_ch["Subgroup Name"]=="G2a2b1a2"]

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
6282,M3302,Y,15104273,T,G,G2a2b1a2,NaN,rs576974702,0,0,1,0,0,1
8480,M3337,Y,16907941,C,T,G2a2b1a2,NaN,rs569270020,0,0,0,1,0,1
9244,M3346,Y,17460050,G,T,G2a2b1a2,NaN,rs551970684,0,0,0,1,0,1

In [65]:
mismatch_path("G2a2b1a2", df_ch).sort_values(by="Subgroup Name")[-50:]

Mismatches: 3 / 83

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
4442,S1435,Y,13658486,C,G,G,Z3258,rs1018446964,0,0,1,0,0,1
4490,Z3262,Y,13676268,G,A,G,NaN,rs1024870708,1,0,0,0,0,1
4507,PF2918,Y,13679469,G,A,G,NaN,rs866067200,1,0,0,0,0,1
4626,PF2920,Y,13824120,T,G,G,NaN,rs1040203200,0,0,1,0,0,1
15816,CTS13035,Y,28783924,C,A,G,PF3133,rs868425858,1,0,0,0,0,1
5128,PF3265,Y,14199646,A,T,G,M3514,rs570554989,0,0,0,1,0,1
5107,CTS2126,Y,14190812,C,T,G,M3512,rs570791365,0,0,0,1,0,1
5099,M3510,Y,14188094,G,T,G,CTS2120;_PF2935,rs531991757,0,0,0,1,0,1
4754,M3501,Y,13987899,A,T,G,CTS1613;_PF2924,rs559330487,0,0,0,1,0,1
6915,CTS4413,Y,15635425,T,C,G2,M3531;_PF2971,rs528832021,0,1,0,0,0,1
626,PF2839,Y,6685638,A,C,G2,M3446,rs565266963,0,2,0,0,0,2
13061,M3594,Y,21663882,C,A,G2,F3226;_PF3064,rs564758491,1,0,0,0,0,1
3068,PF2883,Y,8427005,A,G,G2,F1189;_M3267,rs563631868,0,0,1,0,0,1
12441,M3581,Y,21272579,G,A,G2,PF3047,rs571957672,1,0,0,0,0,1
3310,PF2887,Y,8545324,T,A,G2,F1294;_M3484,rs574354813,1,0,0,0,0,1
3616,F1393,Y,8719593,G,A,G2,M3270;_PF2893,rs577392023,1,0,0,0,0,1
12008,PF3042,Y,19493301,A,G,G2,F3070;_M3578,rs568098392,0,0,1,0,0,1
8355,CTS6316,Y,16817402,C,T,G2,M3545,rs549768787,0,0,0,1,0,1
8467,PF2995,Y,16903051,A,T,G2,F2319;_L496;_M3546,rs35445843,0,0,0,1,0,1
9401,F2529,Y,17571517,A,G,G2a,M3348;_PF3013,rs553390150,1,0,1,0,1,1
15526,PF3141,Y,23973594,T,G,G2a,U5,rs2178500,0,0,1,0,0,1
265,CTS211,Y,2812741,C,T,G2a,M3227;_PF2783,rs574877355,0,0,0,2,0,2
10926,CTS9318,Y,18819146,T,A,G2a,M3362;_PF3026,rs540494999,1,0,0,0,0,1
7614,M3320,Y,16262350,C,T,G2a,CTS5416,rs571028221,0,0,0,2,0,2
6938,PF2972,Y,15660640,C,T,G2a,F1980;_M3309,rs549001775,0,0,0,1,0,1
8408,PF2994,Y,16861108,G,A,G2a,F2301;_M3335,rs528076051,1,0,0,0,0,1
13167,M3401,Y,21760742,C,T,G2a,PF3066,rs566883997,0,0,0,1,0,1
6885,L1259,Y,15615340,C,G,G2a2,CTS4367;_M3308;_PF2970,rs561766566,0,0,1,0,0,1
15495,M3435,Y,23871230,T,C,G2a2b,PF3281,rs546885202,0,0,0,1,1,0
492,PF3254,Y,6425529,C,A,G2a2b,NaN,rs866411369,2,0,0,0,0,2
5761,S148,Y,14692227,T,C,G2a2b,L32;_PF3266;_U8,rs7892988,0,1,0,0,0,1
6865,L30,Y,15604899,C,T,G2a2b,PF3267;_S126,rs34134567,0,0,0,2,0,2
9703,M3352,Y,17787465,A,T,G2a2b,CTS7992,rs562451324,0,0,0,1,0,1
10814,L190,Y,18759690,C,T,G2a2b,M485,rs564870050,0,0,0,1,0,1
12276,F3139,Y,21151007,T,C,G2a2b,PF3274,rs780646639,0,1,0,0,0,1
11289,M3370,Y,19060222,T,G,G2a2b,CTS9763;_PF3271,rs545137085,0,0,1,0,0,1
8923,PF3307,Y,17246670,T,C,G2a2b1,M3344,rs530109689,0,2,0,0,0,2
15173,S25566,Y,23431153,A,G,G2a2b1,M3427,rs547307672,0,0,1,0,0,1
4786,M3281,Y,14002366,G,A,G2a2b1,PF3297,rs549191151,1,0,0,0,0,1
7081,M3315,Y,15752816,G,T,G2a2b1,NaN,rs574356875,0,0,0,1,0,1
15022,PF3319,Y,23327970,G,A,G2a2b1,M3423,rs575331280,2,0,0,0,0,2
11328,M3372,Y,19087143,C,T,G2a2b1,M461,rs547345637,0,0,0,1,0,1
12913,S23266,Y,21562442,G,A,G2a2b1,M9330,rs754187996,1,0,0,0,0,1
14409,M3418,Y,22903313,C,A,G2a2b1,S24848,rs575838386,1,0,0,0,0,1
15118,M3426,Y,23394892,T,G,G2a2b1a,S25516,rs564471781,0,0,1,0,0,1
9788,M3354,Y,17843613,G,A,G2a2b1a,S20284,rs531274744,1,0,0,0,0,1
5366,M3292,Y,14323491,T,C,G2a2b1a,S15820,rs556480164,0,1,0,0,0,1
8480,M3337,Y,16907941,C,T,G2a2b1a2,NaN,rs569270020,0,0,0,1,0,1
6282,M3302,Y,15104273,T,G,G2a2b1a2,NaN,rs576974702,0,0,1,0,0,1
9244,M3346,Y,17460050,G,T,G2a2b1a2,NaN,rs551970684,0,0,0,1,0,1

In [80]:
df_ch[df_ch["Subgroup Name"]=="G2a2b2a"]

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
51,PF3328,Y,6744902,C,T,G2a2b2a,CTS424,rs771484808,0,0,0,1,0,1
116,CTS946,Y,7100848,A,G,G2a2b2a,NaN,rs761514061,0,0,1,0,0,1
1414,P303,Y,21645348,T,C,G2a2b2a,Page108;_PF3340;_S135;_Z765,rs72625365,0,1,0,0,0,1

In [24]:
df_ch[df_ch["Subgroup Name"].isin(["CT", "I","I1"])].sort_values(by="Subgroup Name")

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
96,M5601,Y,7533511,G,A,CT,NaN,NaN,1,0,0,0,0,1
218,M5633,Y,8543804,G,A,CT,NaN,NaN,1,0,0,0,0,1
297,Z17706,Y,9989244,G,T,CT,NaN,NaN,0,0,0,1,0,1
369,CTS2077,Y,14172842,T,G,CT,M5653,NaN,0,0,1,0,0,1
460,L1028,Y,15615637,G,C,CT,CTS4368;_M5680,NaN,0,1,0,0,0,1
597,M5728,Y,17750457,C,T,CT,CTS7933,NaN,0,0,0,1,0,1
685,M5763,Y,19059200,C,A,CT,CTS9760,NaN,1,0,0,0,0,1
735,PF3794,Y,21067903,C,T,I,NaN,NaN,0,0,0,1,0,1
356,CTS1805,Y,14076608,A,G,I1,Z2752,NaN,0,0,1,0,0,1
650,Z2823,Y,18387563,G,T,I1,NaN,NaN,0,0,0,1,0,1

## Run Target .bam

In [6]:
%%time
df_ch, df_der = call_y_bam(df=df, 
                           path_bam="/mnt/archgen/Autorun_eager/eager_outputs/SG/PTN/PTN209/trimmed_bam/PTN209_ss_libmerged_udghalf.trimmed.bam",
                           path_temp='/mnt/archgen/users/hringbauer/git/y_chrom/temp/temp.tsv')

Average Coverage: 9.8489x
#Sites covered: 72393/73148
#Derived Loci:
1280 / 72393 covered>0
CPU times: user 216 ms, sys: 123 ms, total: 339 ms
Wall time: 7.07 s

In [8]:
df_der[-100:-50]

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
1180,PF6432,Y,8194310,C,A,R1b1a1b,NaN,NaN,11,0,0,0,0,11
1181,L265,Y,8149348,A,G,R1b1a1b,PF6431,NaN,0,0,10,0,0,10
1182,CTS1274,Y,7306539,C,G,R1b1a1b,FGC34;_PF6422,NaN,0,0,10,0,0,10
1183,L482,Y,7863189,G,A,R1b1a1b,PF6427,NaN,8,0,0,0,0,8
1184,CTS1415^^,Y,7391109,T,C,R1b1a1b,NaN,NaN,0,3,0,0,0,3
1185,CTS1416^^,Y,7391110,G,A,R1b1a1b,NaN,NaN,3,0,0,0,0,3
1186,L773,Y,7220727,A,G,R1b1a1b,F69;_PF6421;_YSC0000276,NaN,0,0,10,0,0,10
1187,CTS1417,Y,7391117,T,C,R1b1a1b,M11798,NaN,0,1,0,0,0,1
1188,PF5478^^,Y,7391134,T,C,R1b1a1b,CTS1418^^,NaN,0,1,0,0,0,1
1189,CTS1419^^,Y,7391135,G,A,R1b1a1b,NaN,NaN,2,0,0,0,0,2
1190,CTS1420,Y,7391142,A,G,R1b1a1b,PF5479,NaN,0,0,4,0,0,4
1191,PF6494,Y,20811307,G,A,R1b1a1b,NaN,NaN,11,0,0,0,0,11
1192,PF6423^^,Y,7391161,C,T,R1b1a1b,CTS1421^^;_M8208^^,NaN,0,0,0,8,0,8
1193,PF6495,Y,20828795,G,A,R1b1a1b,NaN,NaN,7,0,0,0,0,7
1194,PF6428,Y,7891188,T,C,R1b1a1b,NaN,NaN,0,7,0,0,0,7
1195,CTS1422^^,Y,7391164,G,A,R1b1a1b,M8209^^,NaN,8,0,0,0,0,8
1196,PF6527,Y,24394612,G,A,R1b1a1b,NaN,NaN,14,0,0,0,0,14
1197,PF6493,Y,19462180,C,T,R1b1a1b,CTS10451;_FGC40,NaN,0,0,0,18,0,18
1198,PF6492,Y,19417394,A,C,R1b1a1b,CTS10349;_FGC42,NaN,0,5,0,0,0,5
1199,V3993,Y,19291359,T,C,R1b1a1b,CTS10149;_PF6490,NaN,0,7,0,0,0,7
1200,YSC0000240,Y,24444622,C,T,R1b1a1b,L1351;_PF6528,NaN,0,0,0,13,0,13
1201,PF6425,Y,7762947,T,C,R1b1a1b,NaN,NaN,0,10,0,0,0,10
1202,PF6426,Y,7766712,T,C,R1b1a1b,NaN,NaN,0,6,0,0,0,6
1203,YSC0001293,Y,7073423,G,A,R1b1a1b,CTS894;_PF6420,NaN,9,0,0,0,0,9
1204,PF6265,Y,21554468,G,A,R1b1a1b,NaN,NaN,9,0,0,0,0,9
1205,YSC0000213,Y,20838224,A,G,R1b1a1b,PF6496,NaN,0,0,9,0,0,9
1206,PF6433,Y,8296441,G,T,R1b1a1b,NaN,NaN,0,0,0,14,0,14
1207,YSC0000194,Y,17013730,G,A,R1b1a1b,PF6466,NaN,16,0,0,0,0,16
1208,PF6434,Y,8411202,A,G,R1b1a1b,NaN,NaN,0,0,7,0,0,7
1209,PF6453,Y,14317555,G,A,R1b1a1b,CTS2466,NaN,12,0,0,0,0,12
1210,PF6454,Y,14416216,G,A,R1b1a1b,CTS2664,NaN,19,0,0,0,0,19
1211,FGC54,Y,23379254,G,A,R1b1a1b,CTS11948;_PF6522,NaN,10,0,0,0,0,10
1212,F1794,Y,14522828,G,A,R1b1a1b,PF6455,NaN,8,0,0,0,0,8
1213,S4969,Y,21761275,T,G,R1b1a1b,PF6504,NaN,0,0,4,0,0,4
1214,PF6476,Y,18047475,A,C,R1b1a1b,L749;_YSC0000290,NaN,0,14,0,0,0,14
1215,CTS10834,Y,22796697,T,C,R1b1a1b,NaN,NaN,0,4,0,0,0,4
1216,PF6505,Y,21784286,G,A,R1b1a1b,L1350;_YSC0000225,NaN,11,0,0,0,0,11
1217,PF6517,Y,22739367,T,C,R1b1a1b,M269,NaN,0,5,0,0,0,5
1218,V2713,Y,14956117,C,A,R1b1a1b,CTS3475;_PF6456,NaN,13,0,0,0,0,13
1219,PF6474,Y,17942143,G,A,R1b1a1b,CTS8336;_FGC48,NaN,11,0,0,0,0,11
1220,CTS3575,Y,15037433,C,G,R1b1a1b,PF6457,NaN,0,0,12,0,0,12
1221,CTS8321,Y,17932763,C,T,R1b1a1b,NaN,NaN,0,0,0,7,0,7
1222,PF6516,Y,22621843,G,T,R1b1a1b,M4435;_Z2129,NaN,0,0,0,4,0,4
1223,CTS8052,Y,17813541,C,T,R1b1a1b,FGC45;_PF6473,NaN,0,0,0,17,0,17
1224,CTS7659,Y,17594966,C,G,R1b1a1b,FGC50;_PF6470,NaN,0,0,12,0,0,12
1225,PF6460,Y,15658175,T,C,R1b1a1b,NaN,NaN,0,1,0,0,0,1
1226,PF6461,Y,15732786,T,C,R1b1a1b,CTS4608;_FGC43,NaN,0,10,0,0,0,10
1227,PF6462,Y,15740440,A,G,R1b1a1b,YSC0000180,NaN,1,0,9,0,1,9
1228,PF6509,Y,22190371,A,G,R1b1a1b,NaN,NaN,0,0,7,0,0,7
1229,CTS7400,Y,17461478,T,C,R1b1a1b,FGC33;_PF6469,NaN,0,11,0,0,0,11

In [ ]:
R1b1a1b1a1a
R1b1a1b1a1a2
R1b1a1b1a1a2b
R1b1a1b1a1a2b1

In [12]:
mismatch_path("R1b1a1b1a1a2b1", df_ch).sort_values(by="Subgroup Name")[-50:]

Mismatches: 12 / 274

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
72421,FGC52,Y,28771116,C,G,R1b1a1b,CTS12972;_PF6532,NaN,1,0,8,0,0,8
23026,FGC55,Y,14042701,C,T,R1b1a1b,CTS1738;_PF6449,NaN,0,0,0,15,0,15
32778,PF6460,Y,15658175,T,C,R1b1a1b,NaN,NaN,0,1,0,0,0,1
22732,PF6448,Y,14005779,G,A,R1b1a1b,NaN,NaN,6,0,0,0,0,6
40223,PF6465,Y,16971648,T,G,R1b1a1b,CTS6532,NaN,0,0,5,0,0,5
40450,YSC0000194,Y,17013730,G,A,R1b1a1b,PF6466,NaN,16,0,0,0,0,16
41152,PF6467,Y,17132580,C,T,R1b1a1b,CTS6832,NaN,0,0,0,12,0,12
42013,M12191,Y,17281258,T,G,R1b1a1b,E101;_Y1271,NaN,0,0,10,0,0,10
43289,CTS7400,Y,17461478,T,C,R1b1a1b,FGC33;_PF6469,NaN,0,11,0,0,0,11
44211,CTS7659,Y,17594966,C,G,R1b1a1b,FGC50;_PF6470,NaN,0,0,12,0,0,12
29489,CTS3575,Y,15037433,C,G,R1b1a1b,PF6457,NaN,0,0,12,0,0,12
33245,PF6461,Y,15732786,T,C,R1b1a1b,CTS4608;_FGC43,NaN,0,10,0,0,0,10
45674,CTS8052,Y,17813541,C,T,R1b1a1b,FGC45;_PF6473,NaN,0,0,0,17,0,17
46532,CTS8321,Y,17932763,C,T,R1b1a1b,NaN,NaN,0,0,0,7,0,7
26677,F1794,Y,14522828,G,A,R1b1a1b,PF6455,NaN,8,0,0,0,0,8
46613,PF6474,Y,17942143,G,A,R1b1a1b,CTS8336;_FGC48,NaN,11,0,0,0,0,11
26051,PF6454,Y,14416216,G,A,R1b1a1b,CTS2664,NaN,19,0,0,0,0,19
25287,PF6453,Y,14317555,G,A,R1b1a1b,CTS2466,NaN,12,0,0,0,0,12
23686,YSC0000167,Y,14136291,G,A,R1b1a1b,PF6452,NaN,16,0,0,0,0,16
23283,L762,Y,14079811,T,A,R1b1a1b,PF6450;_YSC0000258,NaN,8,0,0,0,0,8
28982,V2713,Y,14956117,C,A,R1b1a1b,CTS3475;_PF6456,NaN,13,0,0,0,0,13
33311,PF6462,Y,15740440,A,G,R1b1a1b,YSC0000180,NaN,1,0,9,0,1,9
3578,L23,Y,6753511,G,A,R1b1a1b1,PF6534;_S141,NaN,9,0,0,0,0,9
2096,PF6404,Y,3389980,T,C,R1b1a1b1,NaN,NaN,0,1,0,0,0,1
2081,PF6403,Y,3274923,A,C,R1b1a1b1,L478,NaN,0,5,0,0,0,5
47675,CTS8595,Y,18096360,T,G,R1b1a1b1a,YSC0001291,NaN,0,0,1,0,0,1
15668,S167,Y,8502236,G,A,R1b1a1b1a,L51;_M412;_PF6536,NaN,5,0,0,0,0,5
51259,P310,Y,18907236,A,C,R1b1a1b1a1,PF6546;_S129,NaN,0,13,0,0,0,13
27202,L52,Y,14641193,C,T,R1b1a1b1a1,PF6541,NaN,0,0,0,16,0,16
18745,YSC0000082,Y,9084870,G,T,R1b1a1b1a1,PF6540,NaN,0,0,0,11,0,11
48681,PF6545,Y,18248698,A,G,R1b1a1b1a1,P311;_S128,NaN,0,0,7,0,0,7
44161,PF6544,Y,17589518,C,T,R1b1a1b1a1,CTS7650;_FGC44,NaN,0,0,0,7,0,7
45836,L11,Y,17844018,T,C,R1b1a1b1a1a,NaN,NaN,0,10,0,0,0,10
37365,PF6542,Y,16492547,C,T,R1b1a1b1a1a,L151,NaN,0,0,0,13,0,13
38848,S1159,Y,16751825,G,A,R1b1a1b1a1a,PF6543;_YSC0000191,NaN,5,0,0,0,0,5
62953,P312,Y,22157311,C,A,R1b1a1b1a1a2,PF6547;_S116,NaN,11,0,0,0,0,11
30912,S28,Y,15333149,G,A,R1b1a1b1a1a2b,PF6570;_U152,NaN,0,0,0,5,0,0
30911,PF6570,Y,15333149,C,T,R1b1a1b1a1a2b,S28;_U152,NaN,0,0,0,5,0,5
2478,S139,Y,5755550,C,T,R1b1a1b1a1a2b1,L2,NaN,0,0,0,11,0,11
41973,L594,Y,17275043,T,C,R1b1a1b1a1a2b1~,NaN,NaN,0,0,0,8,8,0
29920,L409,Y,15115902,C,T,R1b1a1b1a1a2b1~,NaN,NaN,0,11,0,0,11,0
26543,L408,Y,14495249,T,G,R1b1a1b1a1a2b1~,NaN,NaN,0,0,0,8,8,0
2121,L356,Y,3436428,C,T,R1b1a1b1a1a2b~,NaN,NaN,0,3,0,0,3,0
2113,L343,Y,3436366,C,G,R1b1a1b1a1a2b~,NaN,NaN,0,1,0,0,1,0
7184,A433,Y,7260962,A,C,R1b1a1b1a1a2~,NaN,NaN,11,0,0,0,11,0
32752,L326,Y,15654220,C,T,R1b1a1b1a1a2~,NaN,NaN,0,11,0,0,11,0
32426,M228.1,Y,15591445,T,C,R1b1a1b1a1a2~,NaN,NaN,0,0,0,13,13,0
32751,L289,Y,15654211,G,A,R1b1a1b1a1a2~,NaN,NaN,0,0,11,0,11,0
27816,FGC19610,Y,14765512,G,A,R1b1a1b1a1a2~,A625,NaN,0,0,15,0,15,0
52597,L221,Y,19096343,G,A,R1b1a1b1a1a2~,NaN,NaN,0,0,10,0,10,0

In [ ]:
R1b1a1b1a1a2b1
R1b1a1b1a1a2b1
R1b1a1b1a1a2b
R1b1a1b1a1a2b
R1b1a1b1a1a2

In [58]:
dft = df_ch[df_ch["Subgroup Name"].str.contains("I2")]

der = np.sum(dft["alt#"])
ref = np.sum(dft["ref#"])
print((ref,der))
print(f"Error rate: {der/(ref+der)*100:.4g}%")

(454, 12)
Error rate: 2.575%

In [20]:
dft

,Unnamed: 0,iid,bam#,bam_path
0,0,KSZ001,1,/mnt/archgen/Autorun_eager/eager_outputs/TF/KS...
1,1,KSZ007,1,/mnt/archgen/Autorun_eager/eager_outputs/TF/KS...
2,2,KSZ003,1,/mnt/archgen/Autorun_eager/eager_outputs/TF/KS...
3,3,KSZ002,1,/mnt/archgen/Autorun_eager/eager_outputs/TF/KS...
4,4,KSZ006,1,/mnt/archgen/Autorun_eager/eager_outputs/TF/KS...
...,...,...,...,...
28631,28631,SRC002,0,NaN
28632,28632,SRC003,0,NaN
28633,28633,SRC001,0,NaN
28634,28634,NSV001,0,NaN
28635,28635,PRG001,0,NaN

In [18]:
df_ch[df_ch["Subgroup Name"]=="R1b1a1b1a1a"]

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
37365,PF6542,Y,16492547,C,T,R1b1a1b1a1a,L151,NaN,0,0,0,13,0,13
38848,S1159,Y,16751825,G,A,R1b1a1b1a1a,PF6543;_YSC0000191,NaN,5,0,0,0,0,5
45836,L11,Y,17844018,T,C,R1b1a1b1a1a,NaN,NaN,0,10,0,0,0,10

In [ ]:
df_der[-100:-50]

In [ ]:
R1b1a1b1a1a2b1

In [42]:
%%time
df_ch, df_der = call_y_bam(df=df, 
                           path_bam="/mnt/archgen/users/skourtanioti/MHHAM_varia/Twist_eval_0723/eager_output/eager_output/trimmed_bam/NEV014.A0301_2round.trimmed.bam",
                           path_temp='/mnt/archgen/users/hringbauer/git/y_chrom/temp/temp.tsv')

Average Coverage: 0.0006x
#Sites covered: 37/73148
#Derived Loci:
2 / 37 covered>0
CPU times: user 51.9 ms, sys: 21.1 ms, total: 73 ms
Wall time: 1.18 s

In [82]:
%%time
df_ch, df_der = call_y_bam(df=df, 
                           path_bam="/mnt/archgen/users/skourtanioti/MHHAM_varia/Twist_eval_0723/eager_output/eager_output/trimmed_bam/THE006.A0202_2round.trimmed.bam",
                           path_temp='/mnt/archgen/users/hringbauer/git/y_chrom/temp/temp.tsv')

Average Coverage: 0.1220x
#Sites covered: 7999/73148
#Derived Loci:
215 / 7999 covered>0
CPU times: user 91 ms, sys: 0 ns, total: 91 ms
Wall time: 1.2 s

In [100]:
df_der.to_csv("/mnt/archgen/users/hringbauer/for_nada/y_snps_derived_twist_THE006.tsv", sep="\t")
df_ch.to_csv("/mnt/archgen/users/hringbauer/for_nada/y_snps_all_twist_THE006.tsv", sep="\t")

In [96]:
dft = df_ch[df_ch["Subgroup Name"]=="J1a2a1a2~"]
dft

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
1760,Z2346,Y,8416786,G,A,J1a2a1a2~,PF4663,NaN,1,0,0,0,0,1
2757,PF4839,Y,14045838,C,T,J1a2a1a2~,AM01305;_YSC0000164,NaN,0,0,0,1,0,1
3809,YSC0000181,Y,15756763,T,C,J1a2a1a2~,AM01313;_PF4840,NaN,0,1,0,0,0,1
4237,AM01319,Y,16483304,G,A,J1a2a1a2~,PF4812;_YSC0000188;_Z2362,NaN,1,0,0,0,0,1

In [39]:
dft = df_ch[df_ch["Subgroup Name"].str.contains("E")]

der = np.sum(dft["alt#"])
ref = np.sum(dft["ref#"])
print((ref,der))
print(f"Error rate: {der/(ref+der)*100:.4g}%")

(945, 11)
Error rate: 1.151%

In [ ]:
idx = dft["alt#"]>0
dft[idx]

# Run Koba indivdiuals (Review)

In [44]:
nbrs = [2,7,8,9,11,40]  ### The numbers of Koba Individuals
files = [f"{n}al.bam" for n in nbrs]
folder = "/mnt/archgen/users/hringbauer/data/koba_review/"
paths_bam = [os.path.join(folder, f) for f in files]
paths_bam

['/mnt/archgen/users/hringbauer/data/koba_review/2al.bam',
 '/mnt/archgen/users/hringbauer/data/koba_review/7al.bam',
 '/mnt/archgen/users/hringbauer/data/koba_review/8al.bam',
 '/mnt/archgen/users/hringbauer/data/koba_review/9al.bam',
 '/mnt/archgen/users/hringbauer/data/koba_review/11al.bam',
 '/mnt/archgen/users/hringbauer/data/koba_review/40al.bam']

In [49]:
df = load_snp_file_ISOGG("./data/all_snps.csv")

Index(['Name', 'Subgroup Name', 'Alternate Names', 'rs numbers',
       'Build 37 Number', 'Build 38 Number', 'Mutation Info'],
      dtype='object')
Loaded 92035 SNPs
# Positions available: 91881
# Biallelic SNPs: 91814
# Ref & Alt different: 91811
# Ref & Alt ACTG: 91806
# Unique SNP positions: 73148

In [76]:
%%time
df_ch, df_der = call_y_bam(df=df,
                           path_bed='/mnt/archgen/users/hringbauer/git/y_chrom/data/isogg_snps_chrY.bed',
                           path_bam=paths_bam[2])

Changing 592 ChrY -> Y
Average Coverage: 0.0088x
#Sites covered: 592/73148
#Derived Loci:
11 / 592 covered>0
CPU times: user 62.4 ms, sys: 29.3 ms, total: 91.7 ms
Wall time: 942 ms

In [77]:
df_der[-50:]

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
0,A8852,Y,22996423,T,A,A000-T,NaN,NaN,1,0,0,0,0,1
1,Y8300,Y,23446521,A,G,A1b,NaN,rs764791635,0,0,1,0,0,1
2,M9151,Y,15794075,C,A,BT,NaN,NaN,1,0,0,0,0,1
3,M9188,Y,16946901,G,A,BT,NaN,NaN,1,0,0,0,0,1
4,M9223,Y,17623760,G,A,BT,NaN,NaN,1,0,0,0,0,1
5,M9327,Y,21492793,T,A,BT,NaN,NaN,1,0,0,0,0,1
6,M5631,Y,8396636,G,A,CT,PF292,NaN,1,0,0,0,0,1
7,PF1551,Y,8430640,G,A,E1b1~,M5415,NaN,1,0,0,0,0,1
8,BY165067,Y,16586488,G,C,G2a2b2a1a1b1a1a2a1b2a3a2,NaN,NaN,0,1,0,0,0,1
9,S6601,Y,8839295,G,A,I2a2,NaN,NaN,1,0,0,0,0,1
10,PF4515,Y,8308114,G,A,J,NaN,NaN,1,0,0,0,0,1

## Test Malta Indivdiual

In [31]:
%%time
df_ch, df_der = call_y_bam(df=df, 
                           path_bam="/mnt/archgen/users/hringbauer/data/malta/X5.bam")

Average Coverage: 0.6477x
#Sites covered: 33545/73148
#Derived Loci:
539 / 33545 covered>0
CPU times: user 81.5 ms, sys: 42.8 ms, total: 124 ms
Wall time: 1.42 s

In [ ]:
df_ch

In [ ]:
df_der["Subgroup Name"].str[:3].value_counts()

## Analysis: Browse the output Tables

In [ ]:
df_der1[-150:-100]

In [ ]:
df_t = df_ch1[df_ch1["Subgroup Name"]=="G2a1"].sort_values(by="Subgroup Name")[:40]
df_t

In [208]:
df_t[df_t["alt#"]>0]

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
63388,P312,Y,22157311,C,A,R1b1a1b1a1a2,PF6547;_S116,NaN,51,0,0,0,0,51
63951,BY188,Y,22474043,G,T,R1b1a1b1a1a2c1a1a1a1a1~,NaN,NaN,0,0,7,3,7,3
16892,PF1557.2,Y,8631875,C,A,R1b1a1b1a1a2c1a4b8~,NaN,NaN,1,6,0,0,6,1
38535,BY23092,Y,16635363,G,A,R1b1a1b1a1a2c1a5c3b1b2,NaN,NaN,1,0,13,0,13,1

In [269]:
df_ch[df_ch['Name']=="P312"]

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
51049,P312,Y,22157311,C,A,R1b1a1b1a1a2,PF6547;_S116,NaN,82,0,0,0,0,82

In [29]:
df_ch[df_ch['Subgroup Name']=="R"]

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
18,PF5992,Y,2810583,A,G,R,CTS207;_M600,NaN,0,0,1,0,0,1
378,CTS3622,Y,15078469,C,G,R,PF6037,NaN,0,0,1,0,0,1
412,FGC1168,Y,15667208,G,C,R,NaN,NaN,0,1,0,0,0,1
548,CTS7876,Y,17722802,G,A,R,PF6052,NaN,1,0,0,0,0,1

In [243]:
df_t.columns

Index(['Name', 'chrom', 'pos', 'ref', 'alt', 'Subgroup Name',
       'Alternate Names', 'rs numbers', 'A', 'C', 'G', 'T', 'ref#', 'alt#'],
      dtype='object')

### Extra: Test a Malta Individual as known case
According to publication: H2

In [172]:
%%time
df_ch, df_der = call_y_bam(path_bam="/mnt/archgen/users/hringbauer/data/malta/X5.bam", df=df)

Average Depth: 0.7174x
Derived Read Loci: 588/73148
CPU times: user 40.6 s, sys: 704 ms, total: 41.3 s
Wall time: 41.3 s

In [ ]:
df_ch[idx_der].sort_values(by="Subgroup Name")[:50]

### Test One other Malta Indivdiual

In [161]:
df_ch, df_der = call_y_bam(path_bam="/mnt/archgen/users/hringbauer/data/malta/X9.bam")

Average Depth: 4.0776x
Derived Read Loci: 1208/73148

In [ ]:
df_der[-100:-50]

# Run Berlin samples

In [308]:
%%time
iid = "BEP003"
df_ch, df_der = call_y_bam(df=df, 
                           path_bam=f"/mnt/archgen/MICROSCOPE/eager_outputs/2023-08-21-berlin/trimmed_bam/{iid}_ss.A0101.SG1.trimmed.bam")

Average Coverage: 0.0401x
#Sites covered: 2859/73148
#Derived Loci:
83 / 2859 covered>0
CPU times: user 43.4 ms, sys: 35.8 ms, total: 79.2 ms
Wall time: 882 ms

In [311]:
25/2859

0.008744316194473592

In [ ]:
df_der[-50:]

In [303]:
%%time
iid = "BEP016"
df_ch, df_der = call_y_bam(df=df, 
                           path_bam=f"/mnt/archgen/MICROSCOPE/eager_outputs/2023-08-21-berlin/trimmed_bam/{iid}_ss.A0101.SG1.trimmed.bam")

Average Coverage: 0.0000x
#Sites covered: 1/73148
#Derived Loci:
1 / 1 covered>0
CPU times: user 51.3 ms, sys: 23.6 ms, total: 74.9 ms
Wall time: 1.02 s

In [ ]:
df_der[-10:]

In [290]:
df_ch[df_ch["Subgroup Name"]=="R"]

Empty DataFrame
Columns: [Name, chrom, pos, ref, alt, Subgroup Name, Alternate Names, rs numbers, A, C, G, T, ref#, alt#]
Index: []

### Run Bishop Wichmann

In [5]:
%%time
df_ch, df_der = call_y_bam(df=df, 
                           path_bam="/mnt/archgen/Autorun/Results/Human_1240k/231110_K00233_0372_AHW2T7BBXY_SRdi_Jena0148/WSQ001.A0101.TF1.1/WSQ001.A0101.TF1.1.bam")

Average Coverage: 0.2625x
#Sites covered: 11268/73148
#Derived Loci:
479 / 11268 covered>0
CPU times: user 57.8 ms, sys: 83.5 ms, total: 141 ms
Wall time: 868 ms

In [6]:
df_der[-50:]

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
429,PF6249,Y,8214827,C,T,R1b1,NaN,NaN,0,0,0,1,0,1
430,CTS7585,Y,17545608,G,T,R1b1,NaN,NaN,0,0,0,1,0,1
431,YSC0000022,Y,22889018,G,A,R1b1,L754;_PF6269,NaN,1,0,0,0,0,1
432,PF6524,Y,23452965,T,C,R1b1a1,NaN,NaN,0,1,0,0,0,1
433,CTS11985,Y,23403749,G,A,R1b1a1,PF6523,NaN,1,0,0,0,0,1
434,PF6424,Y,7759944,G,A,R1b1a1,FGC57;_M12189,NaN,3,0,0,0,0,3
435,PF6487,Y,19020340,G,C,R1b1a1,L502,NaN,0,7,0,0,0,7
436,CTS7904,Y,17732408,T,C,R1b1a1,PF6471,NaN,0,1,0,0,0,1
437,CTS9018,Y,18617596,C,T,R1b1a1,PF6484,NaN,0,0,0,2,0,2
438,PF6498,Y,21312064,C,A,R1b1a1,NaN,NaN,1,0,0,0,0,1
439,L585,Y,21358553,G,A,R1b1a1,PF6499,NaN,1,0,0,0,0,1
440,PF6463,Y,16183412,C,A,R1b1a1,NaN,NaN,3,0,0,0,0,3
441,S17,Y,17986687,C,A,R1b1a1,PF6475;_YSC0000269,NaN,3,0,0,0,0,3
442,PF6458,Y,15239181,G,C,R1b1a1,CTS3876,NaN,0,2,0,0,0,2
443,CTS5082,Y,16005138,A,C,R1b1a1,NaN,NaN,0,2,0,0,0,2
444,PF6493,Y,19462180,C,T,R1b1a1b,CTS10451;_FGC40,NaN,0,0,0,2,0,2
445,PF6492,Y,19417394,A,C,R1b1a1b,CTS10349;_FGC42,NaN,0,1,0,0,0,1
446,PF6476,Y,18047475,A,C,R1b1a1b,L749;_YSC0000290,NaN,0,4,0,0,0,4
447,PF6527,Y,24394612,G,A,R1b1a1b,NaN,NaN,2,0,0,0,0,2
448,PF6478,Y,18117193,C,T,R1b1a1b,CTS8627,NaN,0,0,0,1,0,1
449,YSC0001293,Y,7073423,G,A,R1b1a1b,CTS894;_PF6420,NaN,2,0,0,0,0,2
450,CTS623,Y,6912992,T,G,R1b1a1b,PF6419,NaN,0,0,1,0,0,1
451,PF6480,Y,18167403,C,T,R1b1a1b,CTS8728;_L1063;_S13,NaN,0,0,0,1,0,1
452,PF6481,Y,18180446,C,A,R1b1a1b,L500,NaN,2,0,0,0,0,2
453,PF6482,Y,18381735,A,G,R1b1a1b,YSC0000203,NaN,0,0,1,0,0,1
454,FGC52,Y,28771116,C,G,R1b1a1b,CTS12972;_PF6532,NaN,0,0,4,0,0,4
455,L773,Y,7220727,A,G,R1b1a1b,F69;_PF6421;_YSC0000276,NaN,0,0,1,0,0,1
456,CTS8052,Y,17813541,C,T,R1b1a1b,FGC45;_PF6473,NaN,0,0,0,1,0,1
457,PF6441,Y,10062719,C,G,R1b1a1b,NaN,NaN,0,0,1,0,0,1
458,PF6453,Y,14317555,G,A,R1b1a1b,CTS2466,NaN,1,0,0,0,0,1
459,CTS7659,Y,17594966,C,G,R1b1a1b,FGC50;_PF6470,NaN,0,0,1,0,0,1
460,YSC0000219,Y,21222868,C,G,R1b1a1b,PF6497,NaN,0,0,1,0,0,1
461,PF6436,Y,8826595,C,T,R1b1a1b,NaN,NaN,0,0,0,1,0,1
462,L1348,Y,23242935,G,C,R1b1a1b,PF6521;_YSC0000238,NaN,0,2,0,0,0,2
463,L482,Y,7863189,G,A,R1b1a1b,PF6427,NaN,1,0,0,0,0,1
464,PF6503,Y,21581064,C,T,R1b1a1b,NaN,NaN,0,0,0,1,0,1
465,PF6430,Y,8070532,T,A,R1b1a1b,NaN,NaN,1,0,0,0,0,1
466,PF6461,Y,15732786,T,C,R1b1a1b,CTS4608;_FGC43,NaN,0,1,0,0,0,1
467,PF6517,Y,22739367,T,C,R1b1a1b,M269,NaN,0,1,0,0,0,1
468,PF6433,Y,8296441,G,T,R1b1a1b,NaN,NaN,0,0,0,3,0,3
469,L757,Y,19054889,C,T,R1b1a1b,PF6488;_V3721;_YSC0000293,NaN,0,0,0,5,0,5
470,L23,Y,6753511,G,A,R1b1a1b1,PF6534;_S141,NaN,1,0,0,0,0,1
471,PF6545,Y,18248698,A,G,R1b1a1b1a1,P311;_S128,NaN,0,0,1,0,0,1
472,L47,Y,22178569,G,A,R1b1a1b1a1a1c2b1,S170,NaN,1,0,0,0,0,1
473,S352,Y,7400278,G,A,R1b1a1b1a1a1c2b1a1,L163,NaN,2,0,0,0,0,2
474,FGC6218,Y,22034411,G,C,R1b1a1b1a1a1c2b1a1b,NaN,NaN,0,1,0,0,0,1
475,FT104814,Y,13814808,G,A,R1b1a1b1a1a2c1a2b1a1a3b~,NaN,NaN,1,0,0,0,0,1
476,SK2142,Y,2715530,G,A,R2a2b1b2a,NaN,NaN,1,0,0,0,0,1
477,Z41338,Y,17151512,G,A,S1a,NaN,NaN,1,0,0,0,0,1
478,Y108902,Y,22514046,G,A,S4~,NaN,NaN,1,0,0,0,0,1

In [ ]:
R1b1a1b1a1a1c2b1
R1b1a1b1a1a1c2b1a1
R1b1a1b1a1a1c2b1a1b # This is IT!!
R1b1a1b1a1a2c1a2b1a1a3b # Damage

In [31]:
dft = df_ch[df_ch["Subgroup Name"].str[0]=="G"]

der = np.sum(dft["alt#"])
ref = np.sum(dft["ref#"])
print((ref,der))
print(f"Error rate: {der/(ref+der)*100:.4g}%")

(2529, 30)
Error rate: 1.172%

In [ ]:
mismatch_path("R1b1a1b1a1a1c2b1a1b", df_ch)[:50]

In [45]:
dft = df_ch[df_ch["Subgroup Name"]=="R1b1a1b1a1a1c2f~"]
dft

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
9444,Z154,Y,21648778,A,C,R1b1a1b1a1a1c2f~,NaN,NaN,3,0,0,0,3,0

## Run WGS sample from auto_eager

In [23]:
%%time

iid="PTN382"
library = "B0101"
#site=iid[:3]
path_bam = f"/mnt/archgen/Autorun_eager/eager_outputs/SG/{iid[:3]}/{iid}/trimmed_bam/{iid}_ss.B0101_udghalf.trimmed.bam" # Dedupped

#path_bam = "out.bam"
df_ch, df_der = call_y_bam(df=df, path_bam=path_bam)

Average Coverage: 0.5860x
#Sites covered: 31735/73148
#Derived Loci:
619 / 31735 covered>0
CPU times: user 116 ms, sys: 32.4 ms, total: 148 ms
Wall time: 1.72 s

In [25]:
df_der[-100:-50]

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
519,FGC2790,Y,13684562,C,T,J2,Y29592,NaN,0,0,0,1,0,1
520,F4283,Y,19181063,T,A,J2,PF4922,NaN,1,0,0,0,0,1
521,PF4981,Y,19531673,C,T,J2a,CTS10551,NaN,0,0,0,2,0,2
522,F4266,Y,18772238,T,G,J2a,PF4918,NaN,0,0,3,0,0,3
523,PF4977,Y,18772490,C,T,J2a,AM01355;_CTS9245,NaN,0,0,0,1,0,1
524,PF4896,Y,7969047,A,G,J2a,NaN,NaN,0,0,1,0,0,1
525,CTS10134,Y,19283232,A,T,J2a,PF4980,NaN,0,0,0,1,0,1
526,PF4955,Y,7839500,T,A,J2a,NaN,NaN,1,0,0,0,0,1
527,CTS3816,Y,15203000,C,G,J2a,PF4963,NaN,0,0,2,0,0,2
528,F841,Y,6854256,C,T,J2a,PF4948,NaN,0,0,0,1,0,1
529,Z7759,Y,14106407,G,A,J2a,FGC2793,NaN,1,0,0,0,0,1
530,PF4961,Y,14352921,G,A,J2a,CTS2537,NaN,1,0,0,0,0,1
531,CTS9781,Y,19069070,G,A,J2a,PF4978,NaN,1,0,0,0,0,1
532,PF4884,Y,2736889,T,C,J2a,CTS113,NaN,0,1,0,0,0,1
533,PF4927,Y,21337542,C,T,J2a,NaN,NaN,0,0,0,1,0,1
534,PF4958,Y,8474549,T,A,J2a,F4106,NaN,2,0,0,0,0,2
535,PF4983,Y,21318263,T,A,J2a,NaN,NaN,1,0,0,0,0,1
536,L532,Y,16437462,A,G,J2a,NaN,NaN,0,0,1,0,0,1
537,PF4911,Y,16293662,G,A,J2a,CTS5461,NaN,1,0,0,0,0,1
538,F4334,Y,23748578,A,G,J2a,PF4990,NaN,0,0,2,0,0,2
539,PF4967,Y,16196053,C,A,J2a,F2078,NaN,1,0,0,0,0,1
540,CTS5066,Y,15998551,A,C,J2a,NaN,NaN,0,1,0,0,0,1
541,CTS6586,Y,16994287,G,C,J2a,PF4970,NaN,0,1,0,0,0,1
542,F4221,Y,17032059,G,T,J2a,NaN,NaN,0,0,0,1,0,1
543,F4259,Y,18615144,C,A,J2a,PF4976,NaN,2,0,0,0,0,2
544,PF4966,Y,15704139,C,T,J2a,CTS4540,NaN,0,0,0,1,0,1
545,PF4985,Y,21541669,T,C,J2a,NaN,NaN,0,2,0,0,0,2
546,PF4952,Y,7676739,C,T,J2a,NaN,NaN,0,0,0,1,0,1
547,CTS12014,Y,23421475,G,A,J2a,NaN,NaN,2,0,0,0,0,2
548,CTS4403,Y,15632637,G,T,J2a1,PF5096,NaN,0,0,0,2,0,2
549,PF5091,Y,8809001,T,C,J2a1,NaN,NaN,0,4,0,0,0,4
550,PF5114,Y,23402887,A,G,J2a1a,CTS11983,NaN,0,0,1,0,0,1
551,PF4901,Y,9422558,C,A,J2a1a,NaN,NaN,2,0,0,0,0,2
552,Page55,Y,22942897,T,C,J2a1a,L26;_PF5110;_S57,NaN,0,1,0,0,0,1
553,Z1849,Y,8482151,G,T,J2a1a,PF5089,NaN,0,0,0,3,0,3
554,CTS9718,Y,19037126,G,T,J2a1a,PF5102,NaN,0,0,0,1,0,1
555,PF5106,Y,21493159,G,A,J2a1a,NaN,NaN,1,0,0,0,0,1
556,CTS2192,Y,14213941,G,A,J2a1a,PF5094,NaN,1,0,0,0,0,1
557,CTS3547,Y,15003985,G,T,J2a1a,NaN,NaN,0,0,0,1,0,1
558,CTS1230,Y,7284302,C,G,J2a1a1,PF5087,NaN,0,0,2,0,0,2
559,PF5160,Y,8265737,G,A,J2a1a1b,Z2221,NaN,1,0,0,0,0,1
560,AM01358,Y,23141753,A,T,J2a1a1b,AMM342;_PF5163;_Z2222,NaN,0,0,0,1,0,1
561,Z2163,Y,18882240,A,T,J2a1a1b2a1b,PF5436,NaN,0,0,0,1,0,1
562,Z387,Y,6715180,T,C,J2a1a1b2a1b,PF5411,NaN,0,1,0,0,0,1
563,PF5422,Y,14912052,C,G,J2a1a1b2a1b,Z405,NaN,0,0,1,0,0,1
564,Z2154,Y,15580293,C,T,J2a1a1b2a1b,CTS4326,NaN,0,0,0,1,0,1
565,PF5427,Y,17212253,G,T,J2a1a1b2a1b,Z420,NaN,0,0,0,1,0,1
566,Z391,Y,7206433,G,A,J2a1a1b2a1b,PF5412,NaN,1,0,0,0,0,1
567,PF5428,Y,17248041,A,C,J2a1a1b2a1b,Z2170,NaN,0,1,0,0,0,1
568,Z432,Y,19300678,G,A,J2a1a1b2a1b,PF5437,NaN,1,0,0,0,0,1

In [18]:
find_supgroups_der(df_der, subgroup="J2a1a1b2a1b1b")

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
570,PF5430,Y,17357773,G,C,J2a1a1b2a1b1b~,Z423,NaN,0,2,0,0,0,2

In [27]:
mismatch_path("J2a1a1b3", df_ch).sort_values(by="Subgroup Name")#[:50]

Mismatches: 0 / 99

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
18000,CTS6958,Y,17210893,G,A,J,PF4561,NaN,1,0,0,0,0,1
12029,PF4539,Y,14850935,C,G,J,L134,NaN,0,0,1,0,0,1
11669,F1826,Y,14705645,G,A,J,NaN,NaN,1,0,0,0,0,1
13119,PF4543,Y,15277466,G,A,J,CTS3936;_YSC0001275,NaN,1,0,0,0,0,1
24157,PF4586,Y,19460042,G,C,J,CTS10446,NaN,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10292,CTS2167,Y,14204962,G,A,J2a1a~,PF5093,NaN,1,0,0,0,0,1
12476,CTS3546,Y,15003984,A,C,J2a1a~,NaN,NaN,0,1,0,0,0,1
7417,PF5090,Y,8678907,C,T,J2a1a~,NaN,NaN,0,0,0,2,0,2
7794,PF4899,Y,8827398,A,T,J2a~,NaN,NaN,0,0,0,1,0,1
11495,PF4962,Y,14628068,T,C,J2a~,F1810,NaN,0,1,0,0,0,1

In [21]:
calc_error_rate(df_ch, haploclade="R")

(np.int64(4430), np.int64(17))
Error rate: 0.3823%

In [28]:
mismatch_path("J2a1a1b2a1b1b", df_ch).sort_values(by="Subgroup Name")[-50:]

Mismatches: 0 / 101

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
22873,CTS9781,Y,19069070,G,A,J2a,PF4978,NaN,1,0,0,0,0,1
30415,CTS12014,Y,23421475,G,A,J2a,NaN,NaN,2,0,0,0,0,2
30953,F4334,Y,23748578,A,G,J2a,PF4990,NaN,0,0,2,0,0,2
21620,F4259,Y,18615144,C,A,J2a,PF4976,NaN,2,0,0,0,0,2
24364,PF4981,Y,19531673,C,T,J2a,CTS10551,NaN,0,0,0,2,0,2
284,PF4884,Y,2736889,T,C,J2a,CTS113,NaN,0,1,0,0,0,1
17415,CTS6586,Y,16994287,G,C,J2a,PF4970,NaN,0,1,0,0,0,1
1802,F841,Y,6854256,C,T,J2a,PF4948,NaN,0,0,0,1,0,1
4080,PF4952,Y,7676739,C,T,J2a,NaN,NaN,0,0,0,1,0,1
4621,PF4955,Y,7839500,T,A,J2a,NaN,NaN,1,0,0,0,0,1
5059,PF4896,Y,7969047,A,G,J2a,NaN,NaN,0,0,1,0,0,1
6647,PF4958,Y,8474549,T,A,J2a,F4106,NaN,2,0,0,0,0,2
9930,Z7759,Y,14106407,G,A,J2a,FGC2793,NaN,1,0,0,0,0,1
17512,F4221,Y,17032059,G,T,J2a,NaN,NaN,0,0,0,1,0,1
10846,PF4961,Y,14352921,G,A,J2a,CTS2537,NaN,1,0,0,0,0,1
12954,CTS3816,Y,15203000,C,G,J2a,PF4963,NaN,0,0,2,0,0,2
15502,PF4911,Y,16293662,G,A,J2a,CTS5461,NaN,1,0,0,0,0,1
14216,PF4966,Y,15704139,C,T,J2a,CTS4540,NaN,0,0,0,1,0,1
15896,L532,Y,16437462,A,G,J2a,NaN,NaN,0,0,1,0,0,1
15213,PF4967,Y,16196053,C,A,J2a,F2078,NaN,1,0,0,0,0,1
15013,CTS5066,Y,15998551,A,C,J2a,NaN,NaN,0,1,0,0,0,1
14048,CTS4403,Y,15632637,G,T,J2a1,PF5096,NaN,0,0,0,2,0,2
7760,PF5091,Y,8809001,T,C,J2a1,NaN,NaN,0,4,0,0,0,4
25840,PF5106,Y,21493159,G,A,J2a1a,NaN,NaN,1,0,0,0,0,1
30364,PF5114,Y,23402887,A,G,J2a1a,CTS11983,NaN,0,0,1,0,0,1
29117,Page55,Y,22942897,T,C,J2a1a,L26;_PF5110;_S57,NaN,0,1,0,0,0,1
6681,Z1849,Y,8482151,G,T,J2a1a,PF5089,NaN,0,0,0,3,0,3
8351,PF4901,Y,9422558,C,A,J2a1a,NaN,NaN,2,0,0,0,0,2
10350,CTS2192,Y,14213941,G,A,J2a1a,PF5094,NaN,1,0,0,0,0,1
12477,CTS3547,Y,15003985,G,T,J2a1a,NaN,NaN,0,0,0,1,0,1
22770,CTS9718,Y,19037126,G,T,J2a1a,PF5102,NaN,0,0,0,1,0,1
3130,CTS1230,Y,7284302,C,G,J2a1a1,PF5087,NaN,0,0,2,0,0,2
29688,AM01358,Y,23141753,A,T,J2a1a1b,AMM342;_PF5163;_Z2222,NaN,0,0,0,1,0,1
5895,PF5160,Y,8265737,G,A,J2a1a1b,Z2221,NaN,1,0,0,0,0,1
18088,PF5428,Y,17248041,A,C,J2a1a1b2a1b,Z2170,NaN,0,1,0,0,0,1
1376,Z387,Y,6715180,T,C,J2a1a1b2a1b,PF5411,NaN,0,1,0,0,0,1
18004,PF5427,Y,17212253,G,T,J2a1a1b2a1b,Z420,NaN,0,0,0,1,0,1
22312,Z2163,Y,18882240,A,T,J2a1a1b2a1b,PF5436,NaN,0,0,0,1,0,1
2900,Z391,Y,7206433,G,A,J2a1a1b2a1b,PF5412,NaN,1,0,0,0,0,1
13905,Z2154,Y,15580293,C,T,J2a1a1b2a1b,CTS4326,NaN,0,0,0,1,0,1
12205,PF5422,Y,14912052,C,G,J2a1a1b2a1b,Z405,NaN,0,0,1,0,0,1
23642,Z432,Y,19300678,G,A,J2a1a1b2a1b,PF5437,NaN,1,0,0,0,0,1
20671,L70,Y,18077016,T,C,J2a1a1b2a1b1,PF5434;_S287,NaN,0,1,0,0,0,1
18414,PF5430,Y,17357773,G,C,J2a1a1b2a1b1b~,Z423,NaN,0,2,0,0,0,2
31086,PF5115,Y,23838019,G,T,J2a1a~,NaN,NaN,0,0,0,1,0,1
12476,CTS3546,Y,15003984,A,C,J2a1a~,NaN,NaN,0,1,0,0,0,1
7417,PF5090,Y,8678907,C,T,J2a1a~,NaN,NaN,0,0,0,2,0,2
10292,CTS2167,Y,14204962,G,A,J2a1a~,PF5093,NaN,1,0,0,0,0,1
11495,PF4962,Y,14628068,T,C,J2a~,F1810,NaN,0,1,0,0,0,1
7794,PF4899,Y,8827398,A,T,J2a~,NaN,NaN,0,0,0,1,0,1

# Run Beethoven Samples (BEB001 & BEB002)

In [96]:
%%time

iid="BEB001"
library = "A0701"

#path_bam = f"/mnt/archgen/Autorun/Results/Human_RM/240906_LH00454_0052_A22KJNKLT3/{iid}.{library}.RM1.1/{iid}.{library}.RM1.1.bam"
#path_bam = f"/mnt/archgen/users/hringbauer/data/beethoven/{iid}.{library}.RM1.1.l35q25.bam" # Quality filtered
path_bam = f"/mnt/archgen/users/hringbauer/data/beethoven/{iid}.{library}.RM1.1.l35q25.dedup.bam" # Dedupped

#path_bam = "out.bam"
df_ch, df_der = call_y_bam(df=df, path_bam=path_bam)

Average Coverage: 0.0496x
#Sites covered: 3375/73148
#Derived Loci:
70 / 3375 covered>0
CPU times: user 60.6 ms, sys: 9.47 ms, total: 70.1 ms
Wall time: 863 ms

In [97]:
df_der[-50:]

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
20,Y1526,Y,14472971,C,T,CT,NaN,NaN,0,0,0,1,0,1
21,M5778,Y,21281606,G,C,CT,PF1031,NaN,0,1,0,0,0,1
22,M5783,Y,21429988,A,G,CT,NaN,NaN,0,0,1,0,0,1
23,M5705,Y,16822011,A,G,CT,CTS6327,NaN,0,0,1,0,0,1
24,M5747,Y,18179043,C,A,CT,NaN,NaN,1,0,0,0,0,1
25,M5639,Y,8849835,C,A,CT,NaN,NaN,1,0,0,0,0,1
26,CTS11991,Y,23407446,T,G,CT,M5818,NaN,0,0,2,0,0,2
27,BY205426,Y,23124543,G,A,D2,NaN,NaN,1,0,0,0,0,1
28,Z926,Y,14127554,C,T,E1a,CTS1937,NaN,0,0,0,1,0,1
29,Z15217,Y,14104857,G,A,E1a2a2,NaN,NaN,1,0,0,0,0,1
30,Z15236,Y,17546461,G,A,E1a2a2,NaN,NaN,1,0,0,0,0,1
31,CTS8413,Y,17985489,C,T,E1b1a1a1a2a1a3b1a3~,NaN,NaN,0,0,0,1,0,1
32,FGC14098,Y,22529218,C,T,E1b1b1a1b1a25a1~,NaN,NaN,0,0,0,1,0,1
33,PF2775,Y,28650343,C,G,F,CTS12632;_M3771,NaN,0,0,2,0,0,2
34,PF3121,Y,23782951,G,A,G,M3627,rs567796729,1,0,0,0,0,1
35,Y58627,Y,23043665,G,A,G1a2a1,NaN,NaN,1,0,0,0,0,1
36,Z18763,Y,17166146,G,A,G1b,NaN,rs906900562,1,0,0,0,0,1
37,Z44797,Y,21400557,G,A,G2a2b1a2b1,BY21764,rs908964045,1,0,0,0,0,1
38,BY137313,Y,22045401,G,A,G2a2b2a1a1a2~,NaN,rs918300175,1,0,0,0,0,1
39,FGC52673,Y,28781686,C,T,G2a2b2b1b,NaN,NaN,0,0,0,1,0,1
40,ZS3748.2,Y,17815008,G,A,H1a1b1a2~,FGC20902.2,NaN,1,0,0,0,0,1
41,PF3841,Y,23154034,C,T,I,L847;_YSC0000298,NaN,0,0,0,1,0,1
42,PF3569,Y,2688442,T,A,I,CTS48,NaN,1,0,0,0,0,1
43,Y1869,Y,8262092,C,T,I,FGC2413,NaN,0,0,0,1,0,1
44,Y23689,Y,14345762,G,A,I1a1b1d~,NaN,NaN,1,0,0,0,0,1
45,Y6024,Y,14396927,T,G,I2a1b1a1a1b1a~,FGC35437,NaN,0,0,1,0,0,1
46,CTS10057,Y,19232160,C,T,I2a1b1a2,NaN,NaN,0,0,0,1,0,1
47,FGC3574,Y,7311242,A,T,I2a1b1a2b1~,Z163,NaN,0,0,0,1,0,1
48,CTS7934,Y,17750722,A,C,I2a1b1a2b1~,NaN,NaN,0,1,0,0,0,1
49,Y30851,Y,21341396,G,A,I2a1b1a2b2b~,NaN,NaN,1,0,0,0,0,1
50,Y30849,Y,18832386,C,T,I2a1b1a2b2b~,NaN,NaN,0,0,0,1,0,1
51,CTS8500,Y,18058300,G,A,I2a1b1~,NaN,NaN,1,0,0,0,0,1
52,S2479,Y,6661860,T,C,I2a1b1~,L1316,NaN,0,1,0,0,0,1
53,F3102,Y,21040853,A,C,IJ,NaN,NaN,0,1,0,0,0,1
54,Y29689,Y,14124329,G,A,J1a3b~,NaN,NaN,1,0,0,0,0,1
55,CTS10336,Y,19406760,C,A,N1a1a1a1a,NaN,NaN,1,0,0,0,0,1
56,Z34981,Y,21936063,C,T,N1a1a1a1a2a1a1a2a1~,NaN,NaN,0,0,0,1,0,1
57,CTS9915,Y,19144685,G,A,O1b1a1a1a1b1b,NaN,NaN,1,0,0,0,0,1
58,MF8582,Y,19068925,G,A,O2a1b1a1a1a1h1a1,NaN,NaN,1,0,0,0,0,1
59,CTS9362,Y,18849952,C,T,O2a2b1a2a2a1,NaN,rs201958834,0,0,0,1,0,1
60,M1225,Y,16425449,C,T,P1_or_K2b2a,CTS5673;_PF5497;_YSC0001285,rs9786131,0,0,0,1,0,1
61,Y3935,Y,16783169,G,A,Q1a2,F5063,NaN,1,0,0,0,0,1
62,Z35512,Y,14000560,C,T,Q1b1a1a1p,NaN,NaN,0,0,0,1,0,1
63,BZ3494,Y,21842519,C,T,Q1b1a1a1v~,SK1983,NaN,0,0,0,1,0,1
64,Y5269,Y,22068356,C,T,Q1b1a3,NaN,NaN,0,0,0,1,0,1
65,Y2905,Y,8860885,G,A,R1a1a1b1a1a1a1a1,NaN,NaN,1,0,0,0,0,1
66,YP6198,Y,17350910,C,T,R1a1a1b2a1a1a1f2~,NaN,NaN,0,0,0,1,0,1
67,YP5043,Y,17101316,C,T,R1a2a~,NaN,NaN,0,0,0,1,0,1
68,YP5029,Y,14104847,G,A,R1a2a~,NaN,NaN,1,0,0,0,0,1
69,FT192969.2,Y,14472977,C,T,S1a2a,M136585.2,NaN,0,0,0,1,0,1

In [ ]:
mismatch_path("I2a1b1a2b2b", df_ch)[:50]

In [147]:
dft = df_ch[df_ch["Subgroup Name"].str[0]=="G"]

der = np.sum(dft["alt#"])
ref = np.sum(dft["ref#"])
print((ref,der))
print(f"Error rate: {der/(ref+der)*100:.4g}%")

(22961, 124)
Error rate: 0.5371%

In [149]:
idx = df_ch["alt#"]>0
r= np.mean(df_ch[idx]["ref#"])
a = np.mean(df_ch[idx]["alt#"])

print((r,a))

(3.1944444444444446, 19.791666666666668)

In [ ]:
df_ch[idx].sort_values(by="Subgroup Name")[-50:]

## Run .bam of Heinrich II (HRR)

In [4]:
%%time

path_bam = f"/mnt/archgen/Autorun/Results/Human_Shotgun/250723_LH00454_0132_A22TMTFLT4/BMG001.A0101.SG1.3/BMG001.A0101.SG1.3.bam" # Dedupped
df_ch, df_der = call_y_bam(df=df, path_bam=path_bam)

Average Coverage: 0.6659x
#Sites covered: 29697/73148
#Derived Loci:
583 / 29697 covered>0
CPU times: user 46.9 ms, sys: 46.4 ms, total: 93.3 ms
Wall time: 1.39 s

In [82]:
df_ch

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
0,FGC11834,Y,2837997,G,T,NaN,NaN,NaN,0,0,0,3,0,3
1,S10771,Y,7875451,G,A,NaN,NaN,NaN,3,0,1,0,1,3
2,S4268,Y,16808019,C,A,NaN,NaN,NaN,2,0,0,0,0,2
3,S19906,Y,17568588,G,T,NaN,NaN,NaN,0,0,10,0,10,0
4,Z17120,Y,21319306,G,A,NaN,NaN,NaN,1,0,0,0,0,1
5,S23780,Y,21959774,G,T,NaN,NaN,NaN,0,0,0,1,0,1
6,Z17109,Y,22271031,G,T,NaN,NaN,NaN,0,0,0,2,0,2
7,FGC11835,Y,22462454,C,G,NaN,NaN,NaN,0,0,1,0,0,1
8,Z17116,Y,22844182,A,T,NaN,NaN,NaN,0,0,0,1,0,1
9,Z17121,Y,23800016,T,A,NaN,NaN,NaN,5,0,0,0,0,5
10,S4267,Y,28729997,A,G,NaN,NaN,NaN,0,0,1,0,0,1

In [35]:
df_der["Subgroup Name"].str[0].value_counts()

Subgroup Name
B    170
R    110
A     91
C     89
P     39
F     22
E     13
G     13
I      8
O      6
J      4
H      4
N      3
Q      3
D      2
K      2
L      2
M      1
T      1
Name: count, dtype: int64

In [9]:
df_der[-15:]

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
568,CTS7659,Y,17594966,C,G,R1b1a1b,FGC50;_PF6470,NaN,0,0,2,0,0,2
569,PF6477,Y,18095336,A,C,R1b1a1b,CTS8591,NaN,0,2,0,0,0,2
570,PF6403,Y,3274923,A,C,R1b1a1b1,L478,NaN,0,1,0,0,0,1
571,L23,Y,6753511,G,A,R1b1a1b1,PF6534;_S141,NaN,1,0,0,0,0,1
572,S167,Y,8502236,G,A,R1b1a1b1a,L51;_M412;_PF6536,NaN,2,0,0,0,0,2
573,PF6545,Y,18248698,A,G,R1b1a1b1a1,P311;_S128,NaN,0,0,1,0,0,1
574,YSC0000082,Y,9084870,G,T,R1b1a1b1a1,PF6540,NaN,0,0,0,1,0,1
575,P310,Y,18907236,A,C,R1b1a1b1a1,PF6546;_S129,NaN,0,5,0,0,0,5
576,S1159,Y,16751825,G,A,R1b1a1b1a1a,PF6543;_YSC0000191,NaN,1,0,0,0,0,1
577,L132.2,Y,17464197,T,C,R1b1a1b1a1a1c1a2a1~,NaN,NaN,0,2,0,0,0,2
578,Z2,Y,7883339,C,T,R1b1a1b1a1a1c2b2a1b,S511,NaN,0,0,0,1,0,1
579,L196,Y,2887744,C,T,R1b1a1b1a1a2b1b,NaN,NaN,0,0,0,2,0,2
580,FGC17907,Y,22028197,T,G,R1b1a1b1a1a2c1a1i3a,NaN,NaN,0,0,1,0,0,1
581,Y3350,Y,9399594,A,C,R2a2b1a,FGC12665,NaN,0,1,0,0,0,1
582,S12150,Y,9066475,C,T,T1a2a~,NaN,NaN,0,0,0,1,0,1

In [37]:
df_ch[df_ch["Name"].str.contains("S4268")]

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
13068,CTS4268,Y,15531598,A,C,E1a,NaN,NaN,1,0,0,0,1,0

In [8]:
df_ch[df_ch["Subgroup Name"]=="R1b1a1b1a1a"]

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
15880,S1159,Y,16751825,G,A,R1b1a1b1a1a,PF6543;_YSC0000191,NaN,1,0,0,0,0,1

In [ ]:
R1b1a1b1a1a2e1

- R1b1a1b1a1a # That's secure (good path, 1 terminal SNP derived, but G->A)
- R1b1a1b1a1a1c2b2a1b # no
- R1b1a1b1a1a2c1a1i3a #no

In [9]:
find_supgroups_der(df_der, subgroup="R1b1a1b1a1a")

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
577,L132.2,Y,17464197,T,C,R1b1a1b1a1a1c1a2a1~,NaN,NaN,0,2,0,0,0,2
578,Z2,Y,7883339,C,T,R1b1a1b1a1a1c2b2a1b,S511,NaN,0,0,0,1,0,1
579,L196,Y,2887744,C,T,R1b1a1b1a1a2b1b,NaN,NaN,0,0,0,2,0,2
580,FGC17907,Y,22028197,T,G,R1b1a1b1a1a2c1a1i3a,NaN,NaN,0,0,1,0,0,1

In [11]:
calc_error_rate(df_ch, haploclade="G")

(np.int64(8594), np.int64(30))
Error rate: 0.3479%

In [36]:
mismatch_path("R1b1a1b1a1a1b1a1", df_ch).sort_values(by="Subgroup Name")[-50:] 
#R1b1a1b1a1a safe

Mismatches: 6 / 106

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
28393,CTS11985,Y,23403749,G,A,R1b1a1,PF6523,NaN,1,0,0,0,0,1
25569,PF6508,Y,21993844,G,A,R1b1a1b,NaN,NaN,2,0,0,0,0,2
924,PF6409,Y,4352151,G,A,R1b1a1b,NaN,NaN,3,0,0,0,0,3
22551,PF6493,Y,19462180,C,T,R1b1a1b,CTS10451;_FGC40,NaN,0,0,0,1,0,1
28548,PF6525,Y,23476936,G,T,R1b1a1b,NaN,NaN,0,0,0,2,0,2
22901,YSC0000213,Y,20838224,A,G,R1b1a1b,PF6496,NaN,0,0,5,0,0,5
5275,PF6432,Y,8194310,C,A,R1b1a1b,NaN,NaN,1,0,0,0,0,1
25530,PF6507,Y,21983827,C,T,R1b1a1b,NaN,NaN,0,0,0,2,0,2
23299,YSC0000219,Y,21222868,C,G,R1b1a1b,PF6497,NaN,0,0,3,0,0,3
1913,CTS623,Y,6912992,T,G,R1b1a1b,PF6419,NaN,0,0,1,0,0,1
26902,CTS10834,Y,22796697,T,C,R1b1a1b,NaN,NaN,0,2,0,0,0,2
24362,PF6265,Y,21554468,G,A,R1b1a1b,NaN,NaN,1,0,0,0,0,1
24433,PF6503,Y,21581064,C,T,R1b1a1b,NaN,NaN,0,0,0,3,0,3
2743,L773,Y,7220727,A,G,R1b1a1b,F69;_PF6421;_YSC0000276,NaN,0,0,1,0,0,1
4055,PF6425,Y,7762947,T,C,R1b1a1b,NaN,NaN,0,1,0,0,0,1
23926,PF6500,Y,21410840,G,T,R1b1a1b,NaN,NaN,0,0,0,2,0,2
4070,PF6426,Y,7766712,T,C,R1b1a1b,NaN,NaN,0,2,0,0,0,2
29708,FGC52,Y,28771116,C,G,R1b1a1b,CTS12972;_PF6532,NaN,0,0,1,0,0,1
10519,PF6454,Y,14416216,G,A,R1b1a1b,CTS2664,NaN,1,0,0,0,0,1
13623,PF6462,Y,15740440,A,G,R1b1a1b,YSC0000180,NaN,0,0,1,0,0,1
8435,PF6441,Y,10062719,C,G,R1b1a1b,NaN,NaN,0,0,2,0,0,2
8376,S351.1,Y,10008791,C,T,R1b1a1b,L150;_PF6274,NaN,0,0,0,1,0,1
9102,L407,Y,13887941,G,A,R1b1a1b,PF6252,NaN,1,0,0,0,0,1
21754,PF6489,Y,19179540,G,A,R1b1a1b,L1353;_YSC0000294,NaN,1,0,0,0,0,1
9334,FGC55,Y,14042701,C,T,R1b1a1b,CTS1738;_PF6449,NaN,0,0,0,3,0,3
17706,CTS7400,Y,17461478,T,C,R1b1a1b,FGC33;_PF6469,NaN,0,1,0,0,0,1
18069,CTS7659,Y,17594966,C,G,R1b1a1b,FGC50;_PF6470,NaN,0,0,2,0,0,2
8578,PF6443,Y,13511147,C,T,R1b1a1b,NaN,NaN,0,0,0,2,0,2
7278,PF6436,Y,8826595,C,T,R1b1a1b,NaN,NaN,0,0,0,1,0,1
18999,PF6474,Y,17942143,G,A,R1b1a1b,CTS8336;_FGC48,NaN,3,0,0,0,0,3
19266,PF6476,Y,18047475,A,C,R1b1a1b,L749;_YSC0000290,NaN,0,1,0,0,0,1
9598,YSC0000167,Y,14136291,G,A,R1b1a1b,PF6452,NaN,1,0,0,0,0,1
19422,PF6477,Y,18095336,A,C,R1b1a1b,CTS8591,NaN,0,2,0,0,0,2
19503,PF6478,Y,18117193,C,T,R1b1a1b,CTS8627,NaN,0,0,0,1,0,1
5889,PF6434,Y,8411202,A,G,R1b1a1b,NaN,NaN,0,0,1,0,0,1
20501,S3,Y,18719565,T,C,R1b1a1b,PF6485,NaN,0,1,0,0,0,1
5393,L483,Y,8233186,C,T,R1b1a1b,NaN,NaN,0,0,0,3,0,3
8899,PF6444,Y,13816025,G,A,R1b1a1b,NaN,NaN,1,0,0,0,0,1
1429,L23,Y,6753511,G,A,R1b1a1b1,PF6534;_S141,NaN,1,0,0,0,0,1
873,PF6403,Y,3274923,A,C,R1b1a1b1,L478,NaN,0,1,0,0,0,1
6323,S167,Y,8502236,G,A,R1b1a1b1a,L51;_M412;_PF6536,NaN,2,0,0,0,0,2
20949,P310,Y,18907236,A,C,R1b1a1b1a1,PF6546;_S129,NaN,0,5,0,0,0,5
7600,YSC0000082,Y,9084870,G,T,R1b1a1b1a1,PF6540,NaN,0,0,0,1,0,1
19876,PF6545,Y,18248698,A,G,R1b1a1b1a1,P311;_S128,NaN,0,0,1,0,0,1
15880,S1159,Y,16751825,G,A,R1b1a1b1a1a,PF6543;_YSC0000191,NaN,1,0,0,0,0,1
23833,Z369,Y,21380481,C,G,R1b1a1b1a1a1b,NaN,NaN,0,2,0,0,2,0
29545,AM01886,Y,28476394,A,G,R1b1a1b1a1a1b,S262;_Z371,NaN,3,0,0,0,3,0
26919,Z370,Y,22804943,G,T,R1b1a1b1a1a1b,AM01885,NaN,0,0,1,0,1,0
25652,S375,Y,22038215,G,A,R1b1a1b1a1a1b1a,Z372,NaN,0,0,1,0,1,0
8297,FGC36479,Y,9925446,G,A,R1b1a1b1a1a1~,NaN,NaN,0,0,3,0,3,0

In [68]:
df_ch[df_ch["Subgroup Name"].str.contains("R1b1a1b1a1a")]

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
1,BY280,Y,2650297,A,G,R1b1a1b1a1a2c1a1d3b1c1~,NaN,NaN,1,0,0,0,1,0
3,S1468,Y,2650701,G,A,R1b1a1b1a1a2b1c1a1a,Z57,NaN,0,0,1,0,1,0
12,BY55658,Y,2653773,T,A,R1b1a1b1a1a1c2b1b4a3a~,NaN,NaN,0,0,0,1,1,0
28,S3199,Y,2659133,T,G,R1b1a1b1a1a1c2b2b1a1a1e2,CTS9,NaN,0,0,0,1,1,0
50,M8944,Y,2663708,A,T,R1b1a1b1a1a2c1a4b2e~,NaN,NaN,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29616,FGC9657,Y,28654947,A,C,R1b1a1b1a1a2c1a1i,NaN,NaN,1,0,0,0,1,0
29699,DF87,Y,28767492,T,C,R1b1a1b1a1a2e2~,CTS12966,NaN,0,0,0,1,1,0
29710,PF3434.1,Y,28772443,C,T,R1b1a1b1a1a2c1a6e~,NaN,NaN,0,3,0,0,3,0
29773,Z16860,Y,28801992,G,A,R1b1a1b1a1a2c1a2a3a,NaN,NaN,0,0,1,0,1,0
29777,ZW09,Y,28804948,A,T,R1b1a1b1a1a2c1a2b1a1a2,NaN,NaN,2,0,0,0,2,0

In [128]:
df_ch[df_ch["Subgroup Name"]=="R1b1a1b1a1a1c1"]

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
13734,Z156,Y,15780341,A,G,R1b1a1b1a1a1c1,S264,NaN,1,0,0,0,1,0

In [105]:
df[df["Name"]=="S263"]

      Name chrom      pos ref alt  Subgroup Name Alternate Names rs numbers
7207  S263     Y  7246726   C   T  R1b1a1b1a1a1c            Z381        NaN

## Otto I (HRR)

In [5]:
%%time

path_bam = "/mnt/archgen/Autorun/Results/Human_Shotgun/251118_LH00454_0164_A237M3NLT4/WSQ003.A0101.SG1.1/WSQ003.A0101.SG1.1.bam" # Not Dedupped
df_ch, df_der = call_y_bam(df=df, path_bam=path_bam, snip5=1, snip3=1) # Cut bc UDG half

Average Coverage: 0.3238x
#Sites covered: 16107/73148
#Derived Loci:
319 / 16107 covered>0
CPU times: user 67 ms, sys: 23.1 ms, total: 90.1 ms
Wall time: 796 ms

In [9]:
df_der[-50:]

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
269,PF6147,Y,22750583,C,A,R1,M306;_S1,NaN,1,0,0,0,0,1
270,M785,Y,22601068,T,C,R1,L1352;_YSC0000230,NaN,0,3,0,0,0,3
271,CTS3123,Y,14674176,A,C,R1,M670,NaN,0,1,0,0,0,1
272,PF6118,Y,8676330,G,A,R1,M640,NaN,1,0,0,0,0,1
273,CTS4075,Y,15377120,A,G,R1,M682,NaN,0,0,1,0,0,1
274,Y305,Y,13807475,C,A,R1,FGC189,NaN,1,0,0,0,0,1
275,CTS2680,Y,14424045,C,T,R1,NaN,NaN,0,0,0,1,0,1
276,YSC0000288,Y,16742224,A,G,R1,L875;_M706;_PF6131,NaN,0,0,2,0,0,2
277,M643,Y,8738853,G,T,R1,NaN,NaN,0,0,0,2,0,2
278,PF6270,Y,23845409,T,C,R1b,NaN,NaN,0,1,0,0,0,1
279,M343,Y,2887824,C,A,R1b,PF6242,NaN,1,0,0,0,0,1
280,PF6267,Y,21995972,T,A,R1b,L506,NaN,2,0,0,0,0,2
281,CTS2134,Y,14193384,G,A,R1b,NaN,NaN,1,0,0,0,0,1
282,PF6244,Y,7081561,C,T,R1b,CTS910,NaN,0,0,0,2,0,2
283,PF6255,Y,14273103,T,G,R1b,NaN,NaN,0,0,1,0,0,1
284,YSC0000022,Y,22889018,G,A,R1b1,L754;_PF6269,NaN,1,0,0,0,0,1
285,YSC0000211,Y,19504659,T,A,R1b1,L820;_PF6262,NaN,3,0,0,0,0,3
286,PF6266,Y,21558298,G,T,R1b1,L1345;_YSC0000224,NaN,0,0,0,2,0,2
287,PF6249,Y,8214827,C,T,R1b1,NaN,NaN,0,0,0,1,0,1
288,CTS9972,Y,19179606,A,C,R1b1,PF6261,NaN,0,1,0,0,0,1
289,A702,Y,10038192,G,A,R1b1,NaN,NaN,1,0,0,0,0,1
290,PF6506,Y,21801722,G,A,R1b1a1,NaN,NaN,2,0,0,0,0,2
291,PF6265,Y,21554468,G,A,R1b1a1b,NaN,NaN,4,0,0,0,0,4
292,PF6432,Y,8194310,C,A,R1b1a1b,NaN,NaN,1,0,0,0,0,1
293,PF6454,Y,14416216,G,A,R1b1a1b,CTS2664,NaN,3,0,0,0,0,3
294,PF6480,Y,18167403,C,T,R1b1a1b,CTS8728;_L1063;_S13,NaN,0,0,0,1,0,1
295,L407,Y,13887941,G,A,R1b1a1b,PF6252,NaN,3,0,0,0,0,3
296,PF6409,Y,4352151,G,A,R1b1a1b,NaN,NaN,1,0,0,0,0,1
297,CTS8665,Y,18137831,T,C,R1b1a1b,PF6479,NaN,0,1,0,0,0,1
298,M520,Y,4446430,T,A,R1b1a1b,PF6410,NaN,2,0,0,0,0,2
299,PF6493,Y,19462180,C,T,R1b1a1b,CTS10451;_FGC40,NaN,0,0,0,1,0,1
300,PF6525,Y,23476936,G,T,R1b1a1b,NaN,NaN,0,0,0,1,0,1
301,PF6500,Y,21410840,G,T,R1b1a1b,NaN,NaN,0,0,0,2,0,2
302,L483,Y,8233186,C,T,R1b1a1b,NaN,NaN,0,0,0,1,0,1
303,YSC0000219,Y,21222868,C,G,R1b1a1b,PF6497,NaN,0,0,1,0,0,1
304,CTS623,Y,6912992,T,G,R1b1a1b,PF6419,NaN,0,0,1,0,0,1
305,PF6444,Y,13816025,G,A,R1b1a1b,NaN,NaN,1,0,0,0,0,1
306,PF6441,Y,10062719,C,G,R1b1a1b,NaN,NaN,0,0,1,0,0,1
307,PF6494,Y,20811307,G,A,R1b1a1b,NaN,NaN,1,0,0,0,0,1
308,PF6476,Y,18047475,A,C,R1b1a1b,L749;_YSC0000290,NaN,0,1,0,0,0,1
309,YSC0001293,Y,7073423,G,A,R1b1a1b,CTS894;_PF6420,NaN,1,0,0,0,0,1
310,PF6434,Y,8411202,A,G,R1b1a1b,NaN,NaN,0,0,1,0,0,1
311,PF6520,Y,23124367,G,T,R1b1a1b,CTS11468,NaN,0,0,0,3,0,3
312,V2713,Y,14956117,C,A,R1b1a1b,CTS3475;_PF6456,NaN,1,0,0,0,0,1
313,PF6429,Y,7971505,T,C,R1b1a1b,NaN,NaN,0,3,0,0,0,3
314,PF6495,Y,20828795,G,A,R1b1a1b,NaN,NaN,1,0,0,0,0,1
315,S186,Y,15668028,T,C,R1b1a1b1a1a1b1a1,L257,NaN,0,1,0,0,0,1
316,FGC453,Y,15719082,G,A,R1b1a1b1a1a2c1a1a1a1a1c1,S566,NaN,1,0,0,0,0,1
317,A2291,Y,8537060,C,T,R1b1a1b1a1a2c1a3a2a3a,NaN,NaN,0,0,0,1,0,1
318,DF19,Y,14301499,G,T,R1b1a1b1a1a2e,S232,NaN,0,0,0,1,0,1

In [84]:
df_ch

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
0,S17075,Y,15393425,A,G,NaN,NaN,NaN,0,0,1,0,0,1

In [20]:
df_der["Subgroup Name"].str[0].value_counts()

Subgroup Name
B    68
R    65
A    51
C    48
P    27
F    14
G    12
I     4
E     3
K     3
N     2
D     2
J     2
H     1
L     1
O     1
Name: count, dtype: int64

In [31]:
calc_error_rate(df_ch, haploclade="G")

(np.int64(4001), np.int64(15))
Error rate: 0.3735%

In [50]:
df_der[-50:]

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
269,PF6147,Y,22750583,C,A,R1,M306;_S1,NaN,1,0,0,0,0,1
270,M785,Y,22601068,T,C,R1,L1352;_YSC0000230,NaN,0,3,0,0,0,3
271,CTS3123,Y,14674176,A,C,R1,M670,NaN,0,1,0,0,0,1
272,PF6118,Y,8676330,G,A,R1,M640,NaN,1,0,0,0,0,1
273,CTS4075,Y,15377120,A,G,R1,M682,NaN,0,0,1,0,0,1
274,Y305,Y,13807475,C,A,R1,FGC189,NaN,1,0,0,0,0,1
275,CTS2680,Y,14424045,C,T,R1,NaN,NaN,0,0,0,1,0,1
276,YSC0000288,Y,16742224,A,G,R1,L875;_M706;_PF6131,NaN,0,0,2,0,0,2
277,M643,Y,8738853,G,T,R1,NaN,NaN,0,0,0,2,0,2
278,PF6270,Y,23845409,T,C,R1b,NaN,NaN,0,1,0,0,0,1
279,M343,Y,2887824,C,A,R1b,PF6242,NaN,1,0,0,0,0,1
280,PF6267,Y,21995972,T,A,R1b,L506,NaN,2,0,0,0,0,2
281,CTS2134,Y,14193384,G,A,R1b,NaN,NaN,1,0,0,0,0,1
282,PF6244,Y,7081561,C,T,R1b,CTS910,NaN,0,0,0,2,0,2
283,PF6255,Y,14273103,T,G,R1b,NaN,NaN,0,0,1,0,0,1
284,YSC0000022,Y,22889018,G,A,R1b1,L754;_PF6269,NaN,1,0,0,0,0,1
285,YSC0000211,Y,19504659,T,A,R1b1,L820;_PF6262,NaN,3,0,0,0,0,3
286,PF6266,Y,21558298,G,T,R1b1,L1345;_YSC0000224,NaN,0,0,0,2,0,2
287,PF6249,Y,8214827,C,T,R1b1,NaN,NaN,0,0,0,1,0,1
288,CTS9972,Y,19179606,A,C,R1b1,PF6261,NaN,0,1,0,0,0,1
289,A702,Y,10038192,G,A,R1b1,NaN,NaN,1,0,0,0,0,1
290,PF6506,Y,21801722,G,A,R1b1a1,NaN,NaN,2,0,0,0,0,2
291,PF6265,Y,21554468,G,A,R1b1a1b,NaN,NaN,4,0,0,0,0,4
292,PF6432,Y,8194310,C,A,R1b1a1b,NaN,NaN,1,0,0,0,0,1
293,PF6454,Y,14416216,G,A,R1b1a1b,CTS2664,NaN,3,0,0,0,0,3
294,PF6480,Y,18167403,C,T,R1b1a1b,CTS8728;_L1063;_S13,NaN,0,0,0,1,0,1
295,L407,Y,13887941,G,A,R1b1a1b,PF6252,NaN,3,0,0,0,0,3
296,PF6409,Y,4352151,G,A,R1b1a1b,NaN,NaN,1,0,0,0,0,1
297,CTS8665,Y,18137831,T,C,R1b1a1b,PF6479,NaN,0,1,0,0,0,1
298,M520,Y,4446430,T,A,R1b1a1b,PF6410,NaN,2,0,0,0,0,2
299,PF6493,Y,19462180,C,T,R1b1a1b,CTS10451;_FGC40,NaN,0,0,0,1,0,1
300,PF6525,Y,23476936,G,T,R1b1a1b,NaN,NaN,0,0,0,1,0,1
301,PF6500,Y,21410840,G,T,R1b1a1b,NaN,NaN,0,0,0,2,0,2
302,L483,Y,8233186,C,T,R1b1a1b,NaN,NaN,0,0,0,1,0,1
303,YSC0000219,Y,21222868,C,G,R1b1a1b,PF6497,NaN,0,0,1,0,0,1
304,CTS623,Y,6912992,T,G,R1b1a1b,PF6419,NaN,0,0,1,0,0,1
305,PF6444,Y,13816025,G,A,R1b1a1b,NaN,NaN,1,0,0,0,0,1
306,PF6441,Y,10062719,C,G,R1b1a1b,NaN,NaN,0,0,1,0,0,1
307,PF6494,Y,20811307,G,A,R1b1a1b,NaN,NaN,1,0,0,0,0,1
308,PF6476,Y,18047475,A,C,R1b1a1b,L749;_YSC0000290,NaN,0,1,0,0,0,1
309,YSC0001293,Y,7073423,G,A,R1b1a1b,CTS894;_PF6420,NaN,1,0,0,0,0,1
310,PF6434,Y,8411202,A,G,R1b1a1b,NaN,NaN,0,0,1,0,0,1
311,PF6520,Y,23124367,G,T,R1b1a1b,CTS11468,NaN,0,0,0,3,0,3
312,V2713,Y,14956117,C,A,R1b1a1b,CTS3475;_PF6456,NaN,1,0,0,0,0,1
313,PF6429,Y,7971505,T,C,R1b1a1b,NaN,NaN,0,3,0,0,0,3
314,PF6495,Y,20828795,G,A,R1b1a1b,NaN,NaN,1,0,0,0,0,1
315,S186,Y,15668028,T,C,R1b1a1b1a1a1b1a1,L257,NaN,0,1,0,0,0,1
316,FGC453,Y,15719082,G,A,R1b1a1b1a1a2c1a1a1a1a1c1,S566,NaN,1,0,0,0,0,1
317,A2291,Y,8537060,C,T,R1b1a1b1a1a2c1a3a2a3a,NaN,NaN,0,0,0,1,0,1
318,DF19,Y,14301499,G,T,R1b1a1b1a1a2e,S232,NaN,0,0,0,1,0,1

In [ ]:
# Heinrich: R1b1a1b1a1a
# Otto      R1b1a1b    (could be R1b1a1b1a1a)
# otto could be R1b1a1b1a1a1b1a1 (L257, S186 derived)

In [51]:
mismatch_path("R1b1a1b1a1a1b1a1", df_ch).sort_values(by="Subgroup Name")[-50:]

Mismatches: 1 / 64

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
8498,YSC0000288,Y,16742224,A,G,R1,L875;_M706;_PF6131,NaN,0,0,2,0,0,2
4746,Y305,Y,13807475,C,A,R1,FGC189,NaN,1,0,0,0,0,1
6778,CTS4075,Y,15377120,A,G,R1,M682,NaN,0,0,1,0,0,1
10102,CTS8116,Y,17839981,G,A,R1,M730,NaN,1,0,0,0,0,1
3756,PF6118,Y,8676330,G,A,R1,M640,NaN,1,0,0,0,0,1
5896,CTS3123,Y,14674176,A,C,R1,M670,NaN,0,1,0,0,0,1
2015,P242,Y,7647357,G,A,R1,PF6113,NaN,2,0,0,0,0,2
14376,M785,Y,22601068,T,C,R1,L1352;_YSC0000230,NaN,0,3,0,0,0,3
14560,PF6147,Y,22750583,C,A,R1,M306;_S1,NaN,1,0,0,0,0,1
3838,M643,Y,8738853,G,T,R1,NaN,NaN,0,0,0,2,0,2
5644,CTS2680,Y,14424045,C,T,R1,NaN,NaN,0,0,0,1,0,1
13859,PF6267,Y,21995972,T,A,R1b,L506,NaN,2,0,0,0,0,2
408,M343,Y,2887824,C,A,R1b,PF6242,NaN,1,0,0,0,0,1
15826,PF6270,Y,23845409,T,C,R1b,NaN,NaN,0,1,0,0,0,1
5400,PF6255,Y,14273103,T,G,R1b,NaN,NaN,0,0,1,0,0,1
5268,CTS2134,Y,14193384,G,A,R1b,NaN,NaN,1,0,0,0,0,1
1312,PF6244,Y,7081561,C,T,R1b,CTS910,NaN,0,0,0,2,0,2
14744,YSC0000022,Y,22889018,G,A,R1b1,L754;_PF6269,NaN,1,0,0,0,0,1
13195,PF6266,Y,21558298,G,T,R1b1,L1345;_YSC0000224,NaN,0,0,0,2,0,2
12280,YSC0000211,Y,19504659,T,A,R1b1,L820;_PF6262,NaN,3,0,0,0,0,3
2905,PF6249,Y,8214827,C,T,R1b1,NaN,NaN,0,0,0,1,0,1
11768,CTS9972,Y,19179606,A,C,R1b1,PF6261,NaN,0,1,0,0,0,1
4499,A702,Y,10038192,G,A,R1b1,NaN,NaN,1,0,0,0,0,1
13529,PF6506,Y,21801722,G,A,R1b1a1,NaN,NaN,2,0,0,0,0,2
11505,PF6487,Y,19020340,G,C,R1b1a1,L502,NaN,0,0,0,2,0,0
2930,L483,Y,8233186,C,T,R1b1a1b,NaN,NaN,0,0,0,1,0,1
15566,PF6525,Y,23476936,G,T,R1b1a1b,NaN,NaN,0,0,0,1,0,1
15073,PF6520,Y,23124367,G,T,R1b1a1b,CTS11468,NaN,0,0,0,3,0,3
493,PF6409,Y,4352151,G,A,R1b1a1b,NaN,NaN,1,0,0,0,0,1
496,M520,Y,4446430,T,A,R1b1a1b,PF6410,NaN,2,0,0,0,0,2
1030,CTS623,Y,6912992,T,G,R1b1a1b,PF6419,NaN,0,0,1,0,0,1
4911,L407,Y,13887941,G,A,R1b1a1b,PF6252,NaN,3,0,0,0,0,3
13185,PF6265,Y,21554468,G,A,R1b1a1b,NaN,NaN,4,0,0,0,0,4
12971,PF6500,Y,21410840,G,T,R1b1a1b,NaN,NaN,0,0,0,2,0,2
12648,YSC0000219,Y,21222868,C,G,R1b1a1b,PF6497,NaN,0,0,1,0,0,1
12386,PF6495,Y,20828795,G,A,R1b1a1b,NaN,NaN,1,0,0,0,0,1
12359,PF6494,Y,20811307,G,A,R1b1a1b,NaN,NaN,1,0,0,0,0,1
4770,PF6444,Y,13816025,G,A,R1b1a1b,NaN,NaN,1,0,0,0,0,1
12217,PF6493,Y,19462180,C,T,R1b1a1b,CTS10451;_FGC40,NaN,0,0,0,1,0,1
1298,YSC0001293,Y,7073423,G,A,R1b1a1b,CTS894;_PF6420,NaN,1,0,0,0,0,1
5638,PF6454,Y,14416216,G,A,R1b1a1b,CTS2664,NaN,3,0,0,0,0,3
4506,PF6441,Y,10062719,C,G,R1b1a1b,NaN,NaN,0,0,1,0,0,1
10618,PF6480,Y,18167403,C,T,R1b1a1b,CTS8728;_L1063;_S13,NaN,0,0,0,1,0,1
10571,CTS8665,Y,18137831,T,C,R1b1a1b,PF6479,NaN,0,1,0,0,0,1
2557,PF6429,Y,7971505,T,C,R1b1a1b,NaN,NaN,0,3,0,0,0,3
10401,PF6476,Y,18047475,A,C,R1b1a1b,L749;_YSC0000290,NaN,0,1,0,0,0,1
2868,PF6432,Y,8194310,C,A,R1b1a1b,NaN,NaN,1,0,0,0,0,1
3217,PF6434,Y,8411202,A,G,R1b1a1b,NaN,NaN,0,0,1,0,0,1
6278,V2713,Y,14956117,C,A,R1b1a1b,CTS3475;_PF6456,NaN,1,0,0,0,0,1
7209,S186,Y,15668028,T,C,R1b1a1b1a1a1b1a1,L257,NaN,0,1,0,0,0,1

# Area 51

In [13]:
!samtools view /mnt/archgen/users/hringbauer/data/brienzi_capture/A55903.bam 1:33000000-34000000 | wc -l

3052

In [ ]:
path_bed = "/mnt/archgen/users/hringbauer/git/y_chrom/data/isogg_snps.bed"
path_bed = path_bed
df = pd.read_csv(path_bed, sep="\t")

# Redo ISOGG .bed file

In [23]:
path_bed = "/mnt/archgen/users/hringbauer/git/y_chrom/data/isogg_snps.bed"
path_bed_new = "/mnt/archgen/users/hringbauer/git/y_chrom/data/isogg_snps_chrY.bed"

df = pd.read_csv(path_bed, sep= "\t", header=None)
df[0] = "chrY"
df.to_csv(path_bed_new, sep="\t", header=None, index=False)

In [60]:
path_bam = f"/mnt/archgen/Autorun/Results/Human_RM/240906_LH00454_0052_A22KJNKLT3/{iid}.{library}.RM1.1/{iid}.{library}.RM1.1.bam"

In [ ]:
!samtools view $path_bam | head -n 1000000 | cut -f 10 | perl -ne 'chomp;print length($_) . "\n"' | sort | uniq -c

In [65]:
!samtools view -c $path_bam

20030712

In [66]:
!samtools view -h $path_bam | awk 'length($10) > 30 || $1 ~ /^@/' | samtools view -c

18305750